### ISSUE TITLE
Hide "treeview-header"

### ISSUE THREAD

**Issue by Priyal2** [leovo2708/ngx-treeview#101]
We receive items array from backend with its own "All" root tag.

So need to hide the default All option present in the treeview-header.

**Comment by mardon1975** [comment]
Use the config parameter to configure and turn off the ALL root tag your talking about.

I copied this code from the example code in the project.
config = TreeviewConfig.create({
        **hasAllCheckBox: true,**
        hasFilter: true,
        hasCollapseExpand: true,
        decoupleChildFromParent: false,
        maxHeight: 400
}
