### ISSUE TITLE
Selected items in a treeview should be displayed in other treeview.

### ISSUE THREAD

**Issue by Santu9790** [leovo2708/ngx-treeview#102]
Hi,

I have tried displaying the Selected treeview items in other treeview on a button click , but somehow both treeview items are binded(values in the both treeview items are same always).

Please help me in above scenerio.

**Comment by leovo2708** [comment]
Take a screenshot please. Thanks.

**Comment by Santu9790** [comment]
[Ngx-treeview.docx](https://github.com/leovo2708/ngx-treeview/files/1723141/Ngx-treeview.docx).
Screen shots are in the document..

**Comment by leovo2708** [comment]
You need to write more codes to meet your requirement. I think it is not hard

**Comment by Santu9790** [comment]
Im calling below function on the button click: 
this.postitems is the one that im binding to the bottom treeview....

addClick() {
    let checkedItems: any[] = [];
    this.postitems = [];
    console.log(this.values);
    this.selectedItems = [];

    this.values.forEach(element => {
      let parent: DownlineTreeviewItem = element.parent;
      if (!_.isNil(parent) && !checkedItems.includes(parent.item)) {
        debugger;
        this.parentTemp = parent.item;
        for (let i = 0; i < parent.item.children.length; i++) {
          if (parent.item.children[i] != element.item) {
            TreeviewHelper.removeItem(this.parentTemp, parent.item.children[i]);
            i--;
          }
        }
        //this.parentTemp.children.push(element.item);
        checkedItems.push(this.parentTemp);
      } else if (checkedItems.includes(parent.item)) {
        if (this.parentTemp == parent.item) {
          this.parentTemp.children.push(element.item);
        }
      }
    });
    this.postitems = checkedItems;    
  }

**Comment by Santu9790** [comment]
and my Html looks like:

 <div style="margin: auto; max-width: 1000px; margin-bottom: 50px;">
        <ngx-treeview
        [config]="config"
        [items]="items"
        (selectedChange)="onSelectedChange($event);values = $event">
        </ngx-treeview>
      </div>

      <div class="form-group">
          <button type="button" class="btn btn-primary btn-single pull-right" (click)='addClick()'>Add</button>
     </div>

     <div style="margin: auto; max-width: 1000px; margin-bottom: 50px;">
        <ngx-treeview
        [config]="config"
        [items]="postitems"
        (selectedChange)="postValues = $event">
        </ngx-treeview>
      </div>

    </div>

**Comment by Santu9790** [comment]
My html looks like:
 
<div style="margin: auto; max-width: 1000px; margin-bottom: 50px;">
        <ngx-treeview  [config]="config"  [items]="items"        (selectedChange)="onSelectedChange($event);values = $event">
        </ngx-treeview>
     </div>
      <div class="form-group">
          <button type="button" class="btn btn-primary btn-single pull-right" (click)='addClick()'>Add</button>
 </div>
     <div style="margin: auto; max-width: 1000px; margin-bottom: 50px;">
        <ngx-treeview
        [config]="config"
        [items]="postitems"
        (selectedChange)="postValues = $event">
        </ngx-treeview>
      </div>
    </div>

**Comment by mardon1975** [comment]
I ran into this same issue. If you copy the node from the original tree some how it binds to the original nodes state. But if you create a new node with the same data an push that data into the new tree it appears to break the binding issue you are running into. I ran into this same issue.

**Comment by Santu9790** [comment]
Thanks @mardon1975 , Now im able to display the selected ones in another treeview.
