### ISSUE TITLE
Convert ngx-Treeview selected Items to Json.

### ISSUE THREAD

**Issue by Santu9790** [leovo2708/ngx-treeview#104]
Hi,

Is there any way to convert selected Items in ngx-treeview items into the Json? I mean how to convert TreeviewItem[] to json?

**Comment by Santu9790** [comment]
I resolved this issue

**Comment by PrabakarKaruppasamy** [comment]
@Santu9790  can you please share how you resolved this?

**Comment by Santu9790** [comment]
I have used below code to achieve this as i did not find any predefined method that converts to JSON:

createJSON(dataObject: ScenerioSubScenerioList[]) {
    this.jsonObj = [];
    dataObject.forEach(element => {
      let itemExits = this.jsonObj.findIndex(
        item => item.Id == element.scen_Id
      );
      if (itemExits >= 0) {
        var childitem = {};
        childitem["Name"] = element.subScenarioName;
        childitem["Id"] = element.sub_Scen_Id;
        this.jsonObj[itemExits].SubScenerio.push(childitem);
      } else {
        var item = { Name: "", Id: 0, SubScenerio: [] };
        var childitem = {};
        item["Name"] = element.scenarioName;
        item["Id"] = element.scen_Id;
        childitem["Name"] = element.subScenarioName;
        childitem["Id"] = element.sub_Scen_Id;
        //item["SubScenerio"] = childitem;
        item.SubScenerio.push(childitem);
        this.jsonObj.push(item);
      }
    });
  }
