### ISSUE TITLE
How to expand a parent node using the child object (TreeviewItem) programatically?

### ISSUE THREAD

**Issue by DevarshiDave** [leovo2708/ngx-treeview#106]
I want to expand a parent node if a child object is checked. there should be a method for this.

**Comment by leovo2708** [comment]
Yes, you can. You need to lookup parent node and set collapsed value

**Comment by DevarshiDave** [comment]
i am setting child checked property recursively and there is no way i can detect the parent object from it, is there another approach?

**Comment by leovo2708** [comment]
Yes, I built some useful functions, you can check this:
https://github.com/leovo2708/ngx-treeview/blob/master/src/lib/treeview-helper.ts#L47

**Comment by DevarshiDave** [comment]
as of now, there is an setCollapsedRecursive method, but this method is not expanding parent node, it only expands the children of current node.

**Comment by DevarshiDave** [comment]
ok, thanks for the help :)

**Comment by leovo2708** [comment]
You only set collapsed on parent node, it will invoke function setCollapsedRecursive to set collapsed for all children. You don't need to invoke setCollapsedRecursive yourself. The importance is that you need to find parent node with function I provided.

**Comment by DevarshiDave** [comment]
alright, i see your point, i would suggest adding these function to your TreeviewItem class.

**Comment by leovo2708** [comment]
It's already iimported:
import {TreeviewHelper} from 'ngx-treeview'

**Comment by DevarshiDave** [comment]
Can you explain about the two parameters required to use the findParent function?

**Comment by DevarshiDave** [comment]
Its ok, i did it by passing the parent object as a parameter to my recursive function :)

**Comment by leovo2708** [comment]
See this example:
https://github.com/leovo2708/ngx-treeview/blob/master/src/demo/book/book.service.ts#L13

I called node with text 'IT' is first param, node with text 'Python' is second param
=> output of findParam is node with text 'Backend'

**Comment by DevarshiDave** [comment]
Ok i see, one other thing i want to know, is there a way we can have a click event on the node text, or can we use some kind of template to repeat?
P.S the click event should not check the checkbox

**Comment by leovo2708** [comment]
Use custom template. Check my demo.

**Comment by DevarshiDave** [comment]
ok thanks :)

**Comment by DevarshiDave** [comment]
any specific link which has ng-template used with checkboxes? i want to have checkboxes but also a specific click event on node text....

**Comment by leovo2708** [comment]
https://leovo2708.github.io/ngx-treeview/#/advanced

**Comment by DevarshiDave** [comment]
This looks perfect, is there a way i can see the code?

**Comment by aqibnaushad** [comment]
Node is not expanding after setting collapse to false and also tried setting setCollapseRecursive to false , please help

**Comment by SamaneMotahariNejad** [comment]
Hi @leovo2708 ;
I want to add child to each node . could u please help me

**Comment by saumilcmarix** [comment]
Is there any way to get child nodes on the parent expand? I mean lazyload to load the childs
