### ISSUE TITLE
Font Awesome 5 support

### ISSUE THREAD

**Issue by ida-e** [leovo2708/ngx-treeview#107]
Hi!
I would really love if you could make a small change to support Font Awesome version 5. The difference from version 4 is that now they generate a svg-tag instead of using the font-family.

**Example**
_Version 4:_
`<i aria-hidden="true" class="fa fa-caret-down"></i>`
& with the css looking something like this:
`.fa-caret-down:before {
    font-family: FontAwesome;
    content: "\f107";
}`

_Version 5:_ 
`<svg aria-hidden="true" class="svg-inline--fa fa-caret-down fa-w-10" data-prefix="fa" data-icon="caret-down" role="img">
    <path fill="currentColor" d="M31.3 192h257.3c17........"></path>
</svg>`
`<!-- <i aria-hidden="true" class="fa fa-caret-down"></i> -->`

So they´re commenting away the `<i></i>` tag when generating the svg, which leads to that the carets in your treeview is not working.

Thanks for your quick support.

**Comment by ida-e** [comment]
To solve this issue quick, here comes a solution:
In the file `treeview.component.js`:

Down in the template where `<i *ngIf=\"item.children\"` starts and follows with classes of `fa-caret-right` and `fa-caret-down`, edited this tag so it supports both FontAwesome v4 _and_ v5:
`<span class=\"clickable\" *ngIf=\"item.children\" (click)=\"onCollapseExpand()\">    <span *ngIf=\"item.collapsed\">    <i aria-hidden=\"true\" class=\"fa fa-caret-right\"></i>    </span>    <span *ngIf=\"!item.collapsed\">    <i aria-hidden=\"true\" class=\"fa fa-caret-down\"></i>    </span>        </span>`


(Explanation: Since v5 replaces the `<i>` with a `<svg>` tag, it doesn't work with `<i *ngIf="">`, therefore all the `<span>`-tags around the `<i>`-tags...)

**Comment by leovo2708** [comment]
@ida-e Thanks. I have a question: could we use a single template supporting both fa v4 and v5? If yes, you can help me to make a pull request. Thanks.

**Comment by ida-e** [comment]
Yes, the template-change I wrote above works for both v4 and v5. 

Sorry, I'm not so experienced on this page so I don't know how to make a pull request... But this is such a tiny change, please just copy my `<span>`-tag above and replace the old `<i>`-tag...

**Comment by leovo2708** [comment]
Sorry, after reading the document to upgrade from 4 to 5, my syntax for icon font-awesome is correct
https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by ida-e** [comment]
NO! 

Sorry to bother you. Your icon-syntax is correct - yes, but it doesn't work with *ngIf and (click) on the icon-element. 
This is why: The new system replaces the `<i>`-tag with an `<svg>` **which leads to** that the *ngIf and (click) gets replaced - and **does NOT work**!!

So the result is that the arrow isn't clickable and does not change from caret-right to caret-down.
Do you understand?

**Comment by leovo2708** [comment]
Ah, I understood. Thanks. I will update my component right now

**Comment by ida-e** [comment]
Thanks! :)

**Comment by leovo2708** [comment]
Hi @ida-e , I need your help
Please see this code:
```
    <span *ngIf="item.children" (click)="onCollapseExpand()">
      <i aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed" [class.fa-caret-down]="!item.collapsed"></i>
    </span>
```

If Fontawesome replace <i> with <sgv>, I worry that angular tag like [class.fa-caret-right] will not work.

**Comment by ida-e** [comment]
Yes, you're right, that won't work. You need to do like this:
`<span *ngIf="item.children" (click)="onCollapseExpand()">`
    `<span *nfIf="item.collapsed"><i aria-hidden="true" class="fa fa-caret-right"></i></span>`
    `<span *nfIf="!item.collapsed"><i aria-hidden="true" class="fa fa-caret-down"></i></span>` 
`</span>`

**Comment by leovo2708** [comment]
@ida-e Could you tell me how you apply Font Awesome 5?

**Comment by leovo2708** [comment]
@ida-e I see there is an Angular package for FontAwesome: https://github.com/FortAwesome/angular-fontawesome
To use FontAwesome 5 in my component, we should use custom template, the feature it supported. So, your solution is not good in this case.

**Comment by ida-e** [comment]
Of course it's more clean to use an Angular package for FontAwesome. 
Anyhow, my solution supports both FA4 and FA5, which makes it better atm because there's still many people out there using FA4.

**Comment by nheath99** [comment]
Hi, 
I see that this issue is closed, is there a plan to support FontAwesome 5 in the future?
If there are outstanding issues then I would be willing to investigate, with some assistance.

**Comment by ida-e** [comment]
@nheath99 I hope there is a plan. I have big issues with this, the arrows doesn't work when using FontAwesome 5, which makes the treeview unusable...

I have edited treeview.component.js in node_modules so that the arrows works for me, but I have to make theese changes everytime node_modules is cleaned...

**Comment by nheath99** [comment]
@ida-e can you share the code or create a PR?

**Comment by ida-e** [comment]
@nheath99 You can read all my code above.

Instead of this code:
`<span *ngIf="item.children" (click)="onCollapseExpand()">
      <i aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed" [class.fa-caret-down]="!item.collapsed"></i>
</span>`

We have to remove the [class.]=""-attributes 'cuz they don't work with FA5, and instead surround the icons with span-tags that have if-attributes instead:
`<span *ngIf="item.children" (click)="onCollapseExpand()">
<span *ngIf="item.collapsed"><i aria-hidden="true" class="fa fa-caret-right"></i></span>
<span *ngIf="!item.collapsed"><i aria-hidden="true" class="fa fa-caret-down"></i></span>
</span>`

**Comment by nheath99** [comment]
Thanks. It is very simple; I have created a pull request: #151 
I have also changed lines 32-33 with the same principles.
Please add any comments.

**Comment by leovo2708** [comment]
Hi, I am author of this component. I think it can't support both font-awesome 4 & 5.
I suggest the solution to use Font Awesome 5 with my component:
- Use custom item template
- With https://github.com/FortAwesome/angular-fontawesome

**Comment by nheath99** [comment]
@leovo2708 I agree with @ida-e, this is fully compatible with FontAwesome 4.
