### ISSUE TITLE
Breaking down dependencies

### ISSUE THREAD

**Issue by TheSegfault** [leovo2708/ngx-treeview#108]
The README suggest that: "You can customize CSS yourself to break down dependencies to Bootstrap & Font Awesome."

I can't figure it out how to do it.

**Comment by leovo2708** [comment]
My component is using CSS selectors of Bootstrap 4 & Font Awesome. If you are using them, you don't need to write any CSS. But if you don't use them, you need to write some CSS to render.

**Comment by TheSegfault** [comment]
lol
