### ISSUE TITLE
Implemen with REST API

### ISSUE THREAD

**Issue by reachtokish** [leovo2708/ngx-treeview#109]
How to implement with REST API. I am trying to implement but getting this following issue

![image](https://user-images.githubusercontent.com/10685261/36901081-c47a866e-1e4b-11e8-9fab-051e0f30f079.png)

Thanks

**Comment by leovo2708** [comment]
text: '1' // ok
text: 1 // fail

**Comment by reachtokish** [comment]
Lets assume I do not have text and value in my web service. In that case what I have to do ?
