### ISSUE TITLE
How to find root of an item and expand it?

### ISSUE THREAD

**Issue by DevarshiDave** [leovo2708/ngx-treeview#110]
I want to find the root node of an item and call the "setCollapsedRecursive" method to expand the whole node recursively....any thoughts?

**Comment by leovo2708** [comment]
You can write code yourself, as I wrote code to find parent of a item: https://github.com/leovo2708/ngx-treeview/blob/master/src/lib/treeview-helper.ts#L47

**Comment by DevarshiDave** [comment]
Can i fork your code and add this feature?

**Comment by leovo2708** [comment]
Yes, it's ok

**Comment by DevarshiDave** [comment]
Would it be better if i create a pull-request and modify this solution ? or should i fork it? what do you say?

**Comment by leovo2708** [comment]
Fork and then create a pull-request

**Comment by leovo2708** [comment]
And also write unit test if able
