### ISSUE TITLE
Why can't I find the fa-compress class?

### ISSUE THREAD

**Issue by SenMaGe** [leovo2708/ngx-treeview#114]
Why can't I find the fa-compress class? I can't find the fa-compress class, so some of my ICONS don't show up.

**Comment by SenMaGe** [comment]
OK,i got it. Need npm install font-awesome

**Comment by leovo2708** [comment]
Yes, use fontawesome without writing more CSS. But you also write a css to display icon yourself instead of using fontawesome.
