### ISSUE TITLE
"All" Checkbox does not select or unselect other checboxes when in indeterminate state(IE 11)

### ISSUE THREAD

**Issue by casperrr101** [leovo2708/ngx-treeview#116]
I have a list of checkboxes as shown in the attached image.everything works fine in Chrome but in IE 11 when "All" checkbox is in indeterminate state and user clicks on All button it does nothing.all the checkboxes below retain their state.Please see attached image for clearification.

![ngx-treeview bug](https://user-images.githubusercontent.com/14360312/37775689-666587a8-2e05-11e8-88a8-3713df77429b.png)

**Comment by leovo2708** [comment]
This is a known problem on IE11, Edge. It's a browser specific: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/944049/
To fix this problem, you can use this guide: https://stackoverflow.com/questions/10099158/how-to-deal-with-browser-differences-with-indeterminate-checkbox/19447939#19447939

Please fork and build a custom version yourself. This component only supports Chrome & Firefox.
