### ISSUE TITLE
How can I set items to collapse by default when it just created? 

### ISSUE THREAD

**Issue by waynehong789** [leovo2708/ngx-treeview#117]
Because I have a lot of items and child. All items are expanded by default when it is created now. It is very slow. 
Can I set items to collapse when it is created? {  item.collapsed=true } ???

**Comment by abney317** [comment]
For anyone that finds this in the future:
Set the property "collapsed" equal to true for all if your items.

**Comment by mrdixit** [comment]
How did you solve this?

**Comment by abney317** [comment]
> 
> 
> How did you solve this?

The answer to his own question was yes. You set item.collapsed=true on each of your items.

**Comment by waynehong789** [comment]
@mrdixit 
I have not use it any more. "mat-select" is faster than it.

**Comment by mrdixit** [comment]
@abney317 : Thanks. Solved it.
@waynehong789 : Thanks for your response.
