### ISSUE TITLE
click or check  a node ,the tree-view will response error  behavior when the code about binding item.checked ngModel is writer at the end of line

### ISSUE THREAD

**Issue by runtop** [leovo2708/ngx-treeview#12]
click or check  a node ,the tree-view will response error  behavior when the template code about binding item.checked ngModel is writed at the end of line

here is work fine：
` <input type="checkbox" class="form-check-input" 
              [(ngModel)]="item.checked" (ngModelChange)="onCheckedChange()"   />`

and here is work error：
`<input type="checkbox" class="form-check-input" 
             (ngModelChange)="onCheckedChange()"   [(ngModel)]="item.checked"  />`

just only switch the position of  "ngModel" and "ngModelChange".

**Comment by leovo2708** [comment]
Normally, (ngModelChange) should be input after [ngModel].
Thank for your note.
