### ISSUE TITLE
Allow disabled items to be unchecked

### ISSUE THREAD

**Issue by jackjamieson** [leovo2708/ngx-treeview#13]
I have an item set as `disabled: true` and `checked: false` but if the item is `disabled` it will always show the checkbox as checked.

```
const vegetableCategory = new TreeviewItem({
      text: 'Vegetable', value: 2, children: [
        { text: 'Salad', value: 21 },
        { text: 'Potato', value: 22, checked: false, disabled: true }
      ]
    });
```

I tried `vegetableCategory.correctChecked();` but it seems to have no effect.

**Comment by leovo2708** [comment]
Sorry, I'm busy to write unit tests with 97% coverage. I will support your feature.

**Comment by leovo2708** [comment]
@jackjamieson I have a problem if checking on All checkbox, but one item is disabled & unchecked, How should I handle it? Revert All checkbox to unchecked or keep?

**Comment by vikashkronline** [comment]
@leovo2708 Keep disabled item unchanged and place (!) icon with hover message for the same

**Comment by jackjamieson** [comment]
@leovo2708 if the item is disabled it should not be able to be changed.  If it was checked leave it checked if it was unchecked leave it unchecked.

**Comment by leovo2708** [comment]
@jackjamieson My question is about checkbox 'All'? Do you not use it? When I check on checkbox 'All', if one disabled item is unchecked, How should I handle it? Thanks.

**Comment by jackjamieson** [comment]
>  If it was checked leave it checked if it was unchecked leave it unchecked.

**Comment by leovo2708** [comment]
Supported in new version 1.2.0
