### ISSUE TITLE
Can only disabling the parent achieved using ngx-treeview

### ISSUE THREAD

**Issue by akashpatelj09** [leovo2708/ngx-treeview#133]
I am using ngx-treeview and i want to disable only the parent and allow the child to be checked is it possible.

**Comment by leovo2708** [comment]
Yes, custom template is the best solution for any exceptions

**Comment by akashpatelj09** [comment]
yes following that i tried this 

<ng-template #itemTemplate let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
				<div class="form-check">
					<i *ngIf="item.children" (click)="onCollapseExpand()" aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed"
					   [class.fa-caret-down]="!item.collapsed"></i>
					<label class="form-check-label">
						{{item.text}}
					</label>
				</div>
			</ng-template>

			<ngx-treeview [items]="treeGridDataResult" [itemTemplate]="itemTemplate" [config]="ClientsTreeviewConfig">
			</ngx-treeview>

But my requirement is to add checkbox only to the child items and not to parent 
any reference or suggestion in the above code

**Comment by leovo2708** [comment]
Yes, you am going right, but I said, you need to customize itemTemplate, use ngIf to show/hide checkbox if has children or not.

**Comment by leovo2708** [comment]
ngIf here:
https://github.com/leovo2708/ngx-treeview/blob/master/src/lib/treeview.component.html#L6

**Comment by akashpatelj09** [comment]
<ng-template #defaultItemTemplate let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
				<div class="form-inline row-item">
					<i *ngIf="item.children" (click)="onCollapseExpand()" aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed"
					   [class.fa-caret-down]="!item.collapsed"></i>
					<div class="form-check">
						<input *ngIf="!item.children" type="checkbox" class="form-check-input" [(ngModel)]="item.checked" (ngModelChange)="onCheckedChange()" [disabled]="item.disabled"
							   [indeterminate]="item.indeterminate" />
						<label class="form-check-label" (click)="item.checked = !item.checked; onCheckedChange()">
							{{item.text}}
						</label>
					</div>
				</div>
			</ng-template>

			<div class="form-group">
				<label class="control-label">Client/s<span class="startMark">*</span></label>
				<div style="height:300px;overflow:scroll">
					<ngx-treeview [config]="config" [itemTemplate]="defaultItemTemplate" [items]="items" *ngIf="isTreeViewLoaded">
					</ngx-treeview>
				</div>
			</div>


Hey i achieved this but still when i select on the text on parent the children get selected, any idea what could be done to prevent that?
