### ISSUE TITLE
logic for generating tree view data for ngx-drop down tree view

### ISSUE THREAD

**Issue by Abd-exceego** [leovo2708/ngx-treeview#134]
@leovo2708 
I have an array  which looks like this after fetching from RestApi (example):

> [{locationId:1, loationname:INDIA, parentId:0},{ locationId:2, locationname:delhi, parentId:1},{locationId:3,locationname:karnataka,parentId:1} ,{ locationId:4, locationname:banglore, parentId:3},              {locationId:5, locationname:hubli, parentId:3}]

 
taking locationname, locationid and parentId i'm building json data for ngx-drop-down-tree 

Here is the code snippet:

```
items: TreeviewItem[]=[];
value:number;
 fetchedData =[];
treecreate()
{
  for( let  i=0 ; i< this.fetchedData.length ; i++)
  { 
      if( this.fetchedData[i].parent_location_id === 0 )
      {   
         this.generateRoot(this.fetchedData[i].pk_location_id ,this.fetchedData[i].locationname)
      }
      else
      {
        this.generateChild(this.items, this.fetchedData[i].pk_location_id,this.fetchedData[i].locationname,this.fetchedData[i].parent_location_id);
        }
  }
}

generateRoot(pk_id,loc_name)
{
       let tree=new TreeviewItem ({ text:loc_name ,value:pk_id});
       this.items.push(tree);
}

generateChild(temp,pk_id,loc_name,parent_id)
{
    for(var x in temp)
{  
           if(typeof temp[x] == 'object'){
                this.generateChild(temp[x], pk_id,loc_name,parent_id);
    }
    if(temp["value"] == parent_id ){
            if(temp.internalChildren)
               {  
                 temp.internalChildren.push(new TreeviewItem({text:loc_name ,value:pk_id}));
                 break;
                 }//end of inner if condition   
                else
                {
                    temp["children"] =[new TreeviewItem({text:loc_name ,value:pk_id})];
                    break; 
                }
        }
    }
}
```

>output: 
(https://user-images.githubusercontent.com/35985065/39108853-ce7db810-46e7-11e8-994f-50a40611b6da.JPG)

> The problem with this code is it is adding child location Multiple times 
i'm not able to find why this loop is not getting break .
can any one please help me out 
Regards Abdul Quadar.

**Comment by leovo2708** [comment]
Please debug yourself
