### ISSUE TITLE
Angular version mismatch?

### ISSUE THREAD

**Issue by delone-lora** [leovo2708/ngx-treeview#138]
I intended to use your library in my angular project.
But it is giving me an error  called " Template parse errors:
"let-" is only supported on template elements. ("
      <ng-template #defaultItemTemplate [ERROR ->]let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
      "): TreeviewComponent@1:40
"let-" is only supported on template elements. ("
      <ng-template #defaultItemTemplate let-item="item" [ERROR ->]let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">" 

right after importing TreeviewModule.forRoot()

**Comment by leovo2708** [comment]
Upgraded to angular 6
