### ISSUE TITLE
Update dependencies to Angular 6

### ISSUE THREAD

**Issue by dirkkok101** [leovo2708/ngx-treeview#143]
When completing the updates to latest Angular version a warning prevails in the terminal:

ngx-treeview@2.0.6 requires a peer of @angular/common@^5.0.0 but none is installed. 
ngx-treeview@2.0.6 requires a peer of @angular/core@^5.0.0 but none is installed.
ngx-treeview@2.0.6 requires a peer of @angular/forms@^5.0.0 but none is installed.

**Comment by leovo2708** [comment]
Upgrade to angular 6
