### ISSUE TITLE
About ngx-dropdown-treeview

### ISSUE THREAD

**Issue by hzjian** [leovo2708/ngx-treeview#15]
When I add a ngx-dropdown-treeview in my componet like this:
<ngx-dropdown-treeview [config]="config" [items]="items" (selectedChange)="onMenuSelectedChange($event)">
 </ngx-dropdown-treeview>

there only show a  label " 7 options selected" ,what is the reason?  need to add any settings or styles ?

**Comment by leovo2708** [comment]
Please give me your example. Thanks.
