### ISSUE TITLE
i18n should support async/await, promise, or rxjs observables

### ISSUE THREAD

**Issue by mdentremont** [leovo2708/ngx-treeview#153]
Some localization libraries are not synchronous, such as ngx-translate (https://github.com/ngx-translate/core). 

I would be nice if the abstract TreeviewI18n would allow something other than string for the return type - this would make it much easier to use with some of these i18n libraries.

**Comment by leovo2708** [comment]
Do you have any examples or help me to contribute this? Thanks

**Comment by mdentremont** [comment]
@leovo2708 Upon further investigation I discovered that most of these libs tend to have the option of retrieving the translations synchronously, so this issue seems like overkill in hindsight 👍
