### ISSUE TITLE
Question: dropdown append to body

### ISSUE THREAD

**Issue by musker12** [leovo2708/ngx-treeview#160]
## I'm submitting a
<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
[x] Question
</code></pre>

## I'm using
<pre><code>
ngx-treeview: `2.0.6`
</code></pre>

## Description
How can i append dropdown to body ?

**Comment by FritzHerbers** [comment]
You might have a look here how it can be done: [https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-dropdown-panel.component.ts](https://github.com/ng-select/ng-select/blob/master/src/ng-select/ng-dropdown-panel.component.ts).
See "appendTo".

If you have a working change please post back.
