### ISSUE TITLE
throw error on run 'ng serve' or 'ng build' in latest version@1.0.1

### ISSUE THREAD

**Issue by fishen** [leovo2708/ngx-treeview#17]
ERROR in Error encountered resolving symbol values statically. Calling function 'TreeviewModule', function calls are not supported. Consider replacing the function or lambda with a re
ference to an exported function

**Comment by fishen** [comment]
```
import { TreeviewModule } from "ngx-treeview";

@NgModule({
  imports: [
    TreeviewModule.forRoot(),
    ...
    ]
})
export class SomeModule { }
```

**Comment by leovo2708** [comment]
Ok, I will check it.

**Comment by leovo2708** [comment]
Sorry, I configured wrong tsconfig. I built a new version 1.0.5. Please check again. Thanks.

**Comment by NitinTiwari1010** [comment]
I am also getting the same error, what need to do to fix this issue..

**Comment by NitinTiwari1010** [comment]
This issue fixed after taking latest..Thanks

**Comment by leovo2708** [comment]
It's my mistake. Sorry about this.
