### ISSUE TITLE
ngx-treeview with custom selection behavior

### ISSUE THREAD

**Issue by ram-sellamuthu** [leovo2708/ngx-treeview#187]
Hi,

I am trying to define a custom template only to change the selection behavior. I want the selection to change only on click of checkbox. While clicking on the node text, I want to trigger a custom function.

How do I achieve it?

Thanks in advance.

**Comment by ram-sellamuthu** [comment]
I have figured this out and closing the issue

**Comment by PrabakarKaruppasamy** [comment]
@ram-sellamuthu can you please share how you resolved this? I am facing the same

**Comment by ram-sellamuthu** [comment]
Below the template I used:

<ng-template #customTemplate let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
    <div class="form-inline row-item">
        <i *ngIf="item.children" (click)="onCollapseExpand()" aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed"
            [class.fa-caret-down]="!item.collapsed"></i>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" [(ngModel)]="item.checked" **(ngModelChange)="onCheckedChange(); showOrHideComp(item)"**
                [disabled]="item.disabled" [indeterminate]="item.indeterminate" />
            <label [ngClass]="item.selectedStyle || form-check-label" **(click)="highlightComponent(item, true)"**>
                {{item.text}}
            </label>
            
        </div>
    </div>
</ng-template>

<ngx-treeview
    [config]="config"
    [items]="items"
    [itemTemplate]="customTemplate"
    (selectedChange)="onSelectedChange($event)"
    (filterChange)="onFilterChange($event)">
</ngx-treeview>

**Comment by HosseinAbbasabadi** [comment]
can you please share a cleaner code. I am facing the same issue.

**Comment by HosseinAbbasabadi** [comment]
@ram-sellamuthu can you please share a cleaner code. I am facing the same issue.
