### ISSUE TITLE
Not able to see the checkboxes at all.

### ISSUE THREAD

**Issue by bpg168** [leovo2708/ngx-treeview#190]
I have a strange situation, check boxes are not rendered in the tree. but if I click on the items they get selected. Not able to see the check box next to the items.

**Comment by bpg168** [comment]
sorry for the confusions about checkbox


my css stylesheet was overriding it.

as far as i can tell it should be local css style sheet overriding.

**Comment by getupworkdev** [comment]
@bpg168 can you please help me and save my time as what you did to resolve this.


Please help

**Comment by dfong** [comment]
i have a related question: how can i suppress the checkboxes if i don't want them?
