### ISSUE TITLE
Angular-cli build 

### ISSUE THREAD

**Issue by kravda** [leovo2708/ngx-treeview#20]
Try to build application using command: ng build --prod --aot

ng build --prod --aot
Hash: d606c7c0d7f3be6b9d64
Time: 9514ms
chunk    {0} polyfills.6f9a6b71e96c03e848dc.bundle.js (polyfills) 160 kB {4} [initial] [rendered]
chunk    {1} styles.4d33f2e0f832e0f86f03.bundle.css (styles) 334 bytes {4} [initial] [rendered]
chunk    {2} main.1e624e5087b68bca8038.bundle.js (main) 1.09 kB {3} [initial] [rendered]
chunk    {3} vendor.d30f988bc4307961ddf5.bundle.js (vendor) 848 kB [initial] [rendered]
chunk    {4} inline.d4c106170bc3f85f8a51.bundle.js (inline) 0 bytes [entry] [rendered]

ERROR in ENOENT: no such file or directory, open '.\node_modules\ngx-treeview\src\treeview.component.html'

ERROR in ./src/app/main.ts
Module not found: Error: Can't resolve './../$$_gendir/app/app.module.ngfactory' in '.\src\app'
 @ ./src/app/main.ts 2:0-77
 @ multi ./src/app/main.ts

metadata.json contains  treeview.component.html'
{"selector":"ngx-dropdown-treeview","templateUrl":"./dropdown-treeview.component.html"

**Comment by leovo2708** [comment]
I am checking this problem

**Comment by leovo2708** [comment]
Please try again. Sorry for my mistake.

**Comment by kravda** [comment]
fixed
