### ISSUE TITLE
Get Info about the selected Item

### ISSUE THREAD

**Issue by shantanoo-desai** [leovo2708/ngx-treeview#212]
Duplicate of #54  but I am not able to achieve only the checked item. There is no documentation of retrieving only the selected / checked item from the Tree View.

## Code
`itemTemplate` is the same as the demo where the font is a flag instead of a trash bin
```
<ng-template #itemTemplate let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
  <div class="form-inline row-item">
    <i *ngIf="item.children" (click)="onCollapseExpand()" aria-hidden="true" class="fas"
       [class.fa-caret-right]="item.collapsed"
       [class.fa-caret-down]="!item.collapsed"></i>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" [(ngModel)]="item.checked" (ngModelChange)="onCheckedChange()" [disabled]="item.disabled"
             [indeterminate]="item.indeterminate" />
      <label class="form-check-label" (click)="item.checked = !item.checked; onCheckedChange()">
        {{item.text}}
      </label>
      <label class="form-check-label">
        <span><i class="fa fa-flag" aria-hidden="true"></i></span>
      </label>
    </div>
  </div>
```
`ngx-treeview` component
```
<ngx-treeview
        [config]="config"
        [items]="items"
        [itemTemplate]="itemTemplate"
        (selectedChange)="onSelectedChange($event)"
      >
      </ngx-treeview>
```
All I want is to obtain the `TreeviewItem` of the recently triggered or checked item within the tree.

@leovo2708

**Comment by shantanoo-desai** [comment]
There is no other way particularly to trigger but to explicitly add a function `select(item)` by using an `itemTemplate` either in the `<input>` tag or `label`. For basic examples it is not possible to (IMO) to get individual items. 

### Code
```
<div class="form-check">
      <input type="checkbox" class="form-check-input" [(ngModel)]="item.checked" (ngModelChange)="onCheckedChange(); select(item);" [disabled]="item.disabled"
             [indeterminate]="item.indeterminate" />
      <label class="form-check-label" (click)="item.checked = !item.checked; onCheckedChange(); select(item);">
        {{item.text}}
      </label>
      <label class="form-check-label">
        <span><i class="fa fa-flag" aria-hidden="true"></i></span>
      </label>
    </div>
```
`select(item)` is defined as
```
select(item: TreeviewItem) {
   console.log(item);
}
```

Still keeping this issue open in order to understand a better way to get a single checked item upon interaction from user.

**Comment by PrabakarKaruppasamy** [comment]
@shantanoo-desai I am also facing the same issues. Did u find the solution for this?

**Comment by shantanoo-desai** [comment]
@PrabakarKaruppasamy Refer to the [second comment](https://github.com/leovo2708/ngx-treeview/issues/212#issuecomment-486341431)

You can also look into [StackBlitz Example](https://stackblitz.com/edit/qualiexplore)

**Comment by PrabakarKaruppasamy** [comment]
@shantanoo-desai  Can we have similar for uncheck item? It is possible to get the uncecheck item with ngx tree view

```
<ngx-treeview
        [config]="config"
        [items]="items"
        [itemTemplate]="itemTemplate"
        (selectedChange)="onSelectedChange($event)"
      >
      </ngx-treeview>
```
