### ISSUE TITLE
Return all parent values when a child is selected

### ISSUE THREAD

**Issue by soubhikchatterjee** [leovo2708/ngx-treeview#215]
Hello,

I am using this component in one of my major angular projects. The problem I am facing is, when I select a child component the `onSelectedChange()` does not return all its parents, how do I make it return all parent values of a selected child component?

Thanks

**Comment by alissonbovenzo** [comment]
u need replace the default provider  "DefaultTreeviewEventParser" to "TreeviewEventParser" and u can get the property "parent" at onSelectedChange items, one good example is this demo code

https://github.com/leovo2708/ngx-treeview/blob/master/src/demo/product/product.component.ts

**Comment by soubhikchatterjee** [comment]
Thanks for the reply.
