### ISSUE TITLE
17 errors when running tests?

### ISSUE THREAD

**Issue by ModuloM** [leovo2708/ngx-treeview#22]
Hi,

First of all, nice work on this module, very useful, thanks!
I have a question about tests. I have tried to run them and get 17 errors, is it excepted or am I missing something?

Here is my angular-cli versions tree and my package.lock :
https://gist.github.com/ModuloM/198c2aad7c02247d727cc24a1611b9fe

**Comment by leovo2708** [comment]
Hi, how do you run tests? This is output from Travis-CI: https://travis-ci.org/leovo2708/ngx-treeview

**Comment by ModuloM** [comment]
Hi,

Sorry, my bad... I update to 1.0.6, everything is fine (maybe it was some modifications I've made that cause the errors, I should have check my code more precisely). Thanks for your answer anyway and sorry to bother you for nothing.
