### ISSUE TITLE
Parents that are fully selected (checked) during a search and which should become partially selected (-) after text search value is cleared, are instead showing fully blank ().

### ISSUE THREAD

**Issue by emilyspitzer** [leovo2708/ngx-treeview#220]
Hi,

I think I found a bug. We caught this in our own system and then I was able to re-create the same issue in the example solution provided.
 
Any thoughts on how to address this? Some solution or thoughts on what to try would be really helpful.
______

Here is a description of how to re-create the issue in the demo: 

Actions
1. de-select "all" in a filter list 

2. use search function to type in "An"  and then select "all” of the filtered list (see screen 1 in image below)

3. delete text  in search bar (see screen 2 in image below)

**results:**

no parent filters are not showing as partially selected

**expected results:**

parent filters with child filters selected show as partially selected.

![Screen Shot 2019-06-03 at 10 49 49 AM](https://user-images.githubusercontent.com/44007166/58811680-43efa400-85ee-11e9-9b02-6910e8b6c62d.png)

**Comment by prakashsam** [comment]
@emilyspitzer @leovo2708
Same issue for me also.. While search no need to select Parent (Programming). Any solution you found. Please comment here.

**Comment by jkachhia** [comment]
Providing fix in below place will solve issue -> treeview.component.ts
` private updateFilterItems() {
    if (this.filterText !== '') {
      const filterItems: TreeviewItem[] = [];
      const filterText = this.filterText.toLowerCase();
      this.items.forEach(item => {
        const newItem = this.filterItem(item, filterText);
        if (!isNil(newItem)) {
          filterItems.push(newItem);
        }
      });
      this.filterItems = filterItems;
    } else {
      this.filterItems = this.items;
      this.filterItems.forEach(element => {
        if (element instanceof TreeviewItem) {
          element.correctChecked();
        }
      });
    }

    this.updateCheckedOfAll();
  }`

**Comment by emilyspitzer** [comment]
@jkachhia thanks for the response!
