### ISSUE TITLE
Unable to load transpiler to transpile,  SystemJS not loading (traceur.js) 

### ISSUE THREAD

**Issue by subhani1249** [leovo2708/ngx-treeview#23]
Hi, i am using angular4.0
When I try to import this module via SystemJS I get the following error.
![image](https://user-images.githubusercontent.com/10893928/28117373-cd105cc8-672a-11e7-948d-1316e3d300a2.png)

i have implemented as follows
imported ngx-treeview by running this command  **npm install --save ngx-treeview**

in systemconfig
 System.config({
map: {
'ngx-treeview':'npm:ngx-treeview/src'
},
packages: {
 "ngx-treeview": { main: "index.js", defaultExtension: "js" },
        }
})
in app.module.js imported TreeviewModule 
import { TreeviewModule } from 'ngx-treeview';
@NgModule({
    imports: [BrowserModule, FormsModule, RoutingModule,TreeviewModule.forRoot()],
    declarations: [AppComponent],
    providers: [],
    bootstrap: [AppComponent]
})

is there any other dependencies,  can you please have a look into it.
thanks

**Comment by leovo2708** [comment]
Yes, it is currently unable. But I will support build UMD package for SystemJS in future. I will be happy if you help me to contribute this, follow this guide: https://github.com/trekhleb/angular-library-seed. Thanks.
