### ISSUE TITLE
How about allowing single selection from children by configuring a flag in parent item?

### ISSUE THREAD

**Issue by vikashkronline** [leovo2708/ngx-treeview#24]

**Comment by leovo2708** [comment]
Do you mean about using radio button instead of default checked button?

**Comment by jiazijing** [comment]
I have the same request. It's not about radio button, check button is fine. Now the selection model is 'multiple selection', we want to add a 'single selection' model which can select a single value from a tree view.

**Comment by leovo2708** [comment]
You can see my example 4 https://leovo2708.github.io/ngx-treeview/ & do the same.

**Comment by subhabrata2017** [comment]
You guys not have a proper documentation. Its very hard to find things out. :(
