### ISSUE TITLE
Load on demand single check and single branch opening

### ISSUE THREAD

**Issue by CRanaboldo** [leovo2708/ngx-treeview#26]
I have forked your very good project to here https://github.com/CRanaboldo/ngx-treeview.git
This handles load on demand from backend data, single select, and also select the checked element based upon values passed in plus single tree branch opening

**Comment by leovo2708** [comment]
I supported template in new version. You can use it to build a single select component or anything. You can see my example 4 here about a new component ngx-dropdown-treeview-select: https://leovo2708.github.io/ngx-treeview/
