### ISSUE TITLE
TreeviewItem is checked

### ISSUE THREAD

**Issue by sysmat** [leovo2708/ngx-treeview#261]
Why is automatically checked in UI

```typescript
const teenCategory = new TreeviewItem({
      text: 'Teen', value: 19, collapsed: true, checked: false, disabled: false,
      children: [
        { text: 'Adventure', value: 45 },
        { text: 'Science', value: 102 }
      ]
    });
```

Regards

**Comment by eneajaho** [comment]
I'm having this issue in Angular 9.

**Comment by utsavshah06** [comment]
It the children array you will have to set checked=T/F.By default it's set to true.

**Comment by leovo2708** [comment]
Yes, ngx-treeview will correct states of nodes. You explicit set checked=false for child nodes.
