### ISSUE TITLE
Not Able to Toggle Dropdown of treeview

### ISSUE THREAD

**Issue by krishamatya** [leovo2708/ngx-treeview#27]
hy,

i have recently used ngx-dropdown-treeview for my project but i am not able to toggle or open the dropdown , however it is clickable. can you please help me on this. i have followed this git as guide , and didnt find any solutions

**Comment by leovo2708** [comment]
My example is working: https://leovo2708.github.io/ngx-treeview/
Can you tell me more detail?
Thanks.

**Comment by krishamatya** [comment]
Hy Leo,

When I clicked the ngx dropdown tree view it is not opening the treeview. It is clickable indeed but seems disabled. I have installed ngx treeview from npm and havent used the custom library as you have provided in the example since i think it should be given by the installed ngx treeview. and also one thing toggle arrow is also not visible.

And also I have used the web pack for this.

![capture](https://user-images.githubusercontent.com/3993052/29272381-7bbdf768-811f-11e7-80c2-326c39e4b005.PNG)


[RoleAction.zip](https://github.com/leovo2708/ngx-treeview/files/1222256/RoleAction.zip)
[RoleActionMap.service.zip](https://github.com/leovo2708/ngx-treeview/files/1222260/RoleActionMap.service.zip)
[Javra.Payroll.UI.zip](https://github.com/leovo2708/ngx-treeview/files/1222263/Javra.Payroll.UI.zip)

**Comment by carlhussey** [comment]
Same issue, trying to implement this and I have a big grey button that just says "ALL" on it. I an click it and nothing happens. The css gets toggled to `dropdown show` but nothing gets displayed.

**Comment by leovo2708** [comment]
Bootstrap is 4 beta now, and there are a lot of changes. I will upgrade my component to be compatible with it.

**Comment by leovo2708** [comment]
Please upgrade my component to version 1.1.0 if you are using Bootstrap 4 beta. Thanks.
