### ISSUE TITLE
Error message " Cannot read property 'checked' of null"

### ISSUE THREAD

**Issue by ishara119** [leovo2708/ngx-treeview#30]
I am getting data from a web service and trying to bind those to ngx-treeview, however I was able to loop trough the list and mapped to TreeViewItem[]. now all the data are displaying properly and check buttons also working ,
but at the time page loading, im getting above error.
I think thats happening because I have assigned data within the service subscriber but I have no idea how to correct, my code is bellow, if anyone can help me, it would be very much appreciate.

`   public getDataList() {
        this._mydataService.getAllVehicleDetails().subscribe(data => {
            this.items = this.loadTreeviewItems(data)
        }, error => { this.handleErrorResult(error) });`

and the loop is bellow
`GenerateChildItems(child) {
        const sublevel: any[] = [];
        var childrens: TreeviewItem[];
        console.log("1")
        child.forEach((childObj) => {
            if (childObj.subItems != undefined) {
                if (childObj.subItems.length > 0) {
                    childrens = this.GenerateChildItems(childObj.subItems);
                }
            }
            sublevel.push(new TreeviewItem({
                text: childObj.title,
                value: { id: childObj.id, imagePath: childObj.image },
                checked: true,
                children: childrens
            }))
            this.myItemList.push({ id: childObj.id, path: childObj.icon })
        });
        return sublevel;
    }
    public loadTreeviewItems(result): TreeviewItem[] {
        const returnObj: TreeviewItem[] = [];
        if (result != null || result != undefined) {
            result.forEach((mainObj) => {
                console.log("mainObj", mainObj)
                if (mainObj.subItems.length > 0) {
                    var childItems = this.GenerateChildItems(mainObj.subItems);
                    const mydata = new TreeviewItem({
                        text: mainObj.title,
                        value: { id: mainObj.id, imagePath: mainObj.image },
                        checked: false,
                        children: childItems
                    });
                    this.myItemList.push({ id: mainObj.id, path: mainObj.icon })
                    returnObj.push(mydata)
                }
            });
        }
        return returnObj;
    }`

**Comment by leovo2708** [comment]
Please download my demo => setup your data & try, if getting error, please push code here. Thanks.

**Comment by ishara119** [comment]
Hi Leovo,
your demo is working perfectly, its occurred after i bind data from my servicec

**Comment by leovo2708** [comment]
How could I help you? I can't find root cause without your example.

**Comment by ishara119** [comment]
Hi Levo,

I re build treeview according to your demo, somehow error was gone, may be a my mistake, Im sorry
and thank you

**Comment by Js4Life** [comment]
lol
