### ISSUE TITLE
How to use a different TreeviewEventParser

### ISSUE THREAD

**Issue by seza443** [leovo2708/ngx-treeview#32]
Hi, 

First, thanks for this module!

My question is: how can I configure the component to use the *DownlineTreeviewEventParser* ?

Best regards,
Tanguy

**Comment by leovo2708** [comment]
Please see my examples before having a question:
https://github.com/leovo2708/ngx-treeview/blob/master/src/demo/product/product.component.ts#L22

**Comment by seza443** [comment]
Well, thanks for the quick answer
