### ISSUE TITLE
What should I do to pass extra field in TreeviewItem object? 

### ISSUE THREAD

**Issue by rspl-yuvraj** [leovo2708/ngx-treeview#33]
How Can I add an extra field in items of tree?  It supports "text" and "value" key. But I want to add one more field just like below:
`{text: 'xyz', value: '1', name: 'description'}`
I want to use "name" field data as my tooltip content.
Is there any way to do this?

**Comment by leovo2708** [comment]
Use:
`{text: 'xyz', value: {id: 1, name: 'description'}}`

**Comment by rspl-yuvraj** [comment]
Thanx a lot you saved my day.
