### ISSUE TITLE
Is there a way to add custom select function?

### ISSUE THREAD

**Issue by web-dennis** [leovo2708/ngx-treeview#36]

**Comment by leovo2708** [comment]
Please give me more detail.

**Comment by rspl-yuvraj** [comment]
`<ngx-treeview [items]="treeData" [headerTemplate]="treeHeader" [itemTemplate]="tpl" (selectedChange)="onSelectedChange($event)">
</ngx-treeview>`

Here **onSelectedChange** will be your custom select function.
