### ISSUE TITLE
How to select two tree component parallel?

### ISSUE THREAD

**Issue by rspl-yuvraj** [leovo2708/ngx-treeview#37]
I have to use two ngx-treeview component in one page.
`ngx-treeview1 [checkbox1]  |  ngx-treeview2 [checkbox1]`

When I select checkbox1 of ngx-treeview1, then checkbox1 of ngx-treeview2 should be selected and vice versa. How can I achieve this?

**Comment by leovo2708** [comment]
Check example 1: https://leovo2708.github.io/ngx-treeview/
You must use same JSON object on both 2 components.
In my example 1, you can see changes on ngx-treeview also affect on ngx-dropdown-treeview and vice versa.
