### ISSUE TITLE
Option to change [placeholder] text in the Filter?

### ISSUE THREAD

**Issue by BhavinPatel04** [leovo2708/ngx-treeview#38]
Is there any option or a way to just change the placeholder text in the filter. Creating a new header template or custom template just to change the placeholder seems like an overkill. I want to change this in multiple dashboards in my app.

**Comment by leovo2708** [comment]
You use headerTemplate and build your custom component with input [placeholder].

**Comment by BhavinPatel04** [comment]
Instead of creating a component just for [placeholder], can an option be added in [config] to change this?

**Comment by ofekdeitch** [comment]
I need this too.
Customizing the header is quite an overkill IMO
