### ISSUE TITLE
Additional Config options

### ISSUE THREAD

**Issue by blankenshipd001** [leovo2708/ngx-treeview#4]
it would be nice to see a full list of supported config options and it would be great to have the ability to make this a single select instead of multi along with the ability to define what the structure of my data looks like. Ex using nodes or leafs instead of children as the nested categories.

**Comment by leovo2708** [comment]
Sorry, I can't understand your problem. Please give more info. Thanks.

**Comment by blankenshipd001** [comment]
Sure, sorry. 

Currently your component doesn't allow me to force the user to only select a single option. It would be nice to see something like `forceSingle` that when true the user is only allowed to select a single option.


Secondly, your expected structure is hard coded
`text: 'IT', value: 9, children: [
       {
           text: 'Programming', value: 91, children: [{
               text: 'Frontend', value: 911, children: [
                   { text: 'Angular 1', value: 9111 },
                   { text: 'Angular 2', value: 9112 },
                   { text: 'ReactJS', value: 9113 }
               ]
           }]
      }]`

It would be nice if I could define that the "children" is setup as "nodes"

`text: 'IT', value: 9, children: [
       {
           text: 'Programming', value: 91, nodes: [{
               text: 'Frontend', value: 911, nodes: [
                   { text: 'Angular 1', value: 9111 },
                   { text: 'Angular 2', value: 9112 },
                   { text: 'ReactJS', value: 9113 }
               ]
           }]
      }]`

While I'd love to contribute I just don't have time. This is more of a feature request for stuff I can't seem to find anywhere in any select or tree view for Angular 4.

**Comment by gmareater** [comment]
same here

it would be nice to force user to just select one item

**Comment by leovo2708** [comment]
Hello, sorry for late.
I has updated my component. It helps you to make template for header so that you can implement a custom component as your requirement. Please check example 4. Thank you.
