### ISSUE TITLE
how to sort items in same level?

### ISSUE THREAD

**Issue by xsmartweb** [leovo2708/ngx-treeview#40]
how to sort items as asc, or desc in same level?

**Comment by leovo2708** [comment]
sort yourself, my component doesn't support. Order of tree-view items are based on your sorted items.

**Comment by xsmartweb** [comment]
so there is no way to sort items within component?

**Comment by leovo2708** [comment]
no reason to do this :)

**Comment by arkaprava** [comment]
You can use this code for lebel sorting:

private **sortByLebel**(treenodes:any):TreeviewItem{
	let rootNode = treenodes;
	let childNodes =  rootNode.children;
	if(childNodes != null && childNodes.length != 0){
		childNodes.sort(this.alphabeticalSortForTreeNodes);
		for (var idx in childNodes){
			this.sortByLebel(childNodes[idx]);
		}
	}
	return rootNode;	
  }

**alphabeticalSortForTreeNodes**(a, b)
	{
		 var A = a.text;
		 var B = b.text;
		 if (A < B){
			return -1;
		 }else if (A > B){
		   return  1;
		 }else{
		   return 0;
		 }
	}
