### ISSUE TITLE
Parent node value is not included in the selected items

### ISSUE THREAD

**Issue by nghiado** [leovo2708/ngx-treeview#43]
I have couple questions/requests for your great component
1) I have a use case that requires to get all selected values from the tree (not only leaf nodes).
For example Frontend and Backend nodes in your first demo have their own ids, they should be included in the selected results.
2) Is there any way we can add a flag to allow select/deselect child/parent node without updating other nodes? Think about use case like select everything under Programming  except ReactJS
I still want Programming and Front end checked but ReactJS unchecked..
This also related to item 1 since I need to send Front end value back to backend.
Thanks

**Comment by leovo2708** [comment]
Question 1: using TreeviewEventParser like in my example 5 https://leovo2708.github.io/ngx-treeview/. You can get list of checked from root to leaf.

Question 2: Yes, you can. You can update checked of your TreeviewItem object. But it will not update checked of parent, you must do this yourself. You should write a helper to handle this.

**Comment by nghiado** [comment]
Thanks for quick resposne @leovo2708.
Yes, #1, I was thinking about create a custom TreeviewEventParser to return a flat list of selected items.
About #2, can you give an example?
What I was thinking is in **TreeviewItemComponent**
```
onCheckedChange = (skipChildrenCheck) => {
        const checked = this.item.checked;
        if (!_.isNil(this.item.children)&& !skipChildrenCheck) {
            this.item.children.forEach(child => child.setCheckedRecursive(checked));
        }

        this.checkedChange.emit(checked);
    }
    onChildCheckedChange(child: TreeviewItem, checked: boolean, skipParentUpdate) {
        if (this.item.checked !== checked && !skipParentUpdate) {
            let itemChecked = true;
            for (const tmpChild of this.item.children) {
                if (!tmpChild.checked) {
                    itemChecked = false;
                    break;
                }
            }

            this.item.checked = itemChecked;
        }

        this.checkedChange.emit(checked);
    }
```

I tried to override the `onCheckedChange` and `onChildCheckedChange` but the component is not exported from the lib so not so sure how I can achieve this.

**Comment by leovo2708** [comment]
If I support option {disabled: true, checked: false} for item ReactJS, does it rescue you?

**Comment by nghiado** [comment]
The behavior I'm looking for is 'parent/children' can be checked/unchecked independently while we can leverage existing features like custom template, filter etc. This can be config at the tree level or item template.

**Comment by leovo2708** [comment]
I think you can use itemTemplate. It can help you.

**Comment by nghiado** [comment]
@leovo2708 I need a way to emit this event `this.checkedChange.emit(checked)`; using itemTemplate without calling `onCheckedChange` and `onChildCheckedChange`.
I think this requires a minor change in `TreeviewItemComponent` and `TreeviewItemTemplateContext`.

**Comment by leovo2708** [comment]
Please help me to create pull request. Thanks.

**Comment by leovo2708** [comment]
Published in new version 1.2.2.

**Comment by arunkumar1811** [comment]
Hi,
"selectedChange" event has been fired when selecting Parent but the $event array is empty. But the expected would be event array with Parent node value.

Its working as expected when I select child nodes. I'm using the latest verion 1.2.3. 

Parent and child nodes can be selected independently by setting decoupleParentChild= true in the config.

**Comment by rwasan** [comment]
same issue please let me know if it's fixed

**Comment by thienvuact11** [comment]
> same issue please let me know if it's fixed

Just append this code to function **filterItem** like this:
![image](https://github.com/leovo2708/ngx-treeview/assets/92499225/bfb82b55-94ad-4d45-9fa9-870e28a99220)
