### ISSUE TITLE
disable cascading check

### ISSUE THREAD

**Issue by jgritten** [leovo2708/ngx-treeview#44]
I would like to request an option where each check box would operate independently. With this option enabled, when a parent with children is checked, the children are not automatically checked. Vice versa, if all the children are checked, the parent would not be.

thanks

**Comment by jgritten** [comment]
i just read this has been requesting in another thread. closed

**Comment by seza443** [comment]
Can you reference this other thread please ?

**Comment by jgritten** [comment]
issue discussed in - **Parent node value is not included in the selected items #43**
