### ISSUE TITLE
Tree Style in table format

### ISSUE THREAD

**Issue by nm-a** [leovo2708/ngx-treeview#45]
Hi @leovo2708 ,
Hope you are doing well.
Today I am trying to create one Table Style tree view (kind of Tree List) using template option. Unfortunately I couldn't make this in Table format. The complete tree is loading inside first column. Can you please recommend any other approach to achieve this.

`                        <table class="table table-bordered ipro-table">
                            <thead>
                                <tr>
                                    <th style="text-align:center !important;">Name</th>
                                    <th style="text-align:center !important;">Code</th>
                                    <th style="text-align:center !important;">Manage</th>
                                </tr>
                            </thead>
                            <tbody>
                                <ngx-treeview [items]="treeviewItemsNodes" [itemTemplate]="accountsTreeTemplate" [config]="treeConfig">
                                </ngx-treeview>
                            </tbody>
                        </table>`

![image](https://user-images.githubusercontent.com/7089157/30435712-1180450a-9988-11e7-8fdf-c054d1f0eb27.png)

**Comment by leovo2708** [comment]
Using table in tree is not a good idea. Sorry, I can't help you.
