### ISSUE TITLE
Selecting parent node checkbox without selecting child checkboxes

### ISSUE THREAD

**Issue by narsivc** [leovo2708/ngx-treeview#46]
It would be nice to be able to select parent node checkbox without selecting child checkboxes; ie Every checkbox is independent. It also means that selecting all child checkboxes does not automatically select parent checkbox. This should ideally be configurable in TreeviewConfig. Let me know if you want me to contribute this feature.

**Comment by narsivc** [comment]
Just realized that issue #43 is referring to the same feature though the title is not misleading ! Closing this ask.

**Comment by leovo2708** [comment]
Could you give me the reason why you want checkbox should be independent. A example of real case is good. Thanks.
