### ISSUE TITLE
Tree View Displays No Items Found

### ISSUE THREAD

**Issue by winni4eva** [leovo2708/ngx-treeview#47]
I get no items found displayed when i pass an object to the items property..

------------------------------Component--------------------------------
myItems = {
                        text: 'IT', value: 9, children: [
                            {
                                text: 'Programming', value: 91, children: [{
                                    text: 'Frontend', value: 911, children: [
                                        { text: 'Angular 1', value: 9111 },
                                        { text: 'Angular 2', value: 9112 },
                                        { text: 'ReactJS', value: 9113 }
                                    ]
                                }, {
                                    text: 'Backend', value: 912, children: [
                                        { text: 'C#', value: 9121 },
                                        { text: 'Java', value: 9122 },
                                        { text: 'Python', value: 9123, checked: false }
                                    ]
                                }]
                            },
                            {
                                text: 'Networking', value: 92, children: [
                                    { text: 'Internet', value: 921 },
                                    { text: 'Security', value: 922 }
                                ]
                            }
                        ]
                        };
-----------------------------------------------------------------------------

--------------------------------template---------------------------------
<ngx-treeview
  [config]="config"
  [items]="myItems"
  (selectedChange)="onSelectedChange($event)">
</ngx-treeview>

---------------------------------------------------------------------------------

I also tried wrapping my object in the TreeviewItem class but I still get the same error messsage..

**Comment by leovo2708** [comment]
Yes, you are using wrong binding data, it must be a list of TreeviewItem object, not JSON object.

**Comment by winni4eva** [comment]
It will be nice if you can provide me with some example data which works, I just tried this but it still returns the same error message.

`this._treeViewItem = new TreeviewItem({
        text: 'Vegetable', value: 2, children: [
            { text: 'Salad', value: 21 },
            { text: 'Potato', value: 22 }
        ]
        });
        this._treeViewItem.children.push(new TreeviewItem({ text: 'Mushroom', value: 23, checked: false }));
        this._treeViewItem.correctChecked();`

**Comment by leovo2708** [comment]
It's your mistake, I gave some examples but maybe you did't read them. My demo is here:
https://leovo2708.github.io/ngx-treeview/
And code is here: https://github.com/leovo2708/ngx-treeview/tree/master/src/demo

**Comment by winni4eva** [comment]
Thanks, got it working with the books example. Maybe you could add the demo link to the Readme. Great job.

**Comment by soubhikchatterjee** [comment]
For anyone else who is still struggling with displaying the items, the items should be an array of `TreeviewItem`.

Working code here:

```
// Your.component.ts
import { TreeviewItem } from "ngx-treeview";

export class YourComponent implements OnInit {

  public items = [
    new TreeviewItem({
      text: "Vegetable",
      value: 2,
      checked: false,
      children: []
    })
  ];
}

// Your.component.html
    <ngx-treeview
      [config]="config"
      [items]="items"
      (selectedChange)="onSelectedChange($event)"
    >
    </ngx-treeview>
```

This is all!

**Comment by MatheusPetrachin** [comment]
If I receive JSON from a Rest API can I do something like this? if so how can i do it, i have the same error

export class BookService {

  permissions: TreeviewItem[] = [];

  constructor(
    private permissionService: PermissionService
  ) { };


  getBooks(): TreeviewItem[] {

    this.permissionService.getPermissionTree(89).subscribe(p => {
      this.permissions = p;
      return [this.permissions]
    });

    return [];
  }
}

**Comment by leovo2708** [comment]
what error? You should read my examples, I define value property of TreeviewItem is any, you can use it.
