### ISSUE TITLE
Doesn't work with standard JSON

### ISSUE THREAD

**Issue by IAMtheIAM** [leovo2708/ngx-treeview#49]
Hi, thanks for making this. Here is my object

```js
  "isAuthenticated": true,
  "userInfo": {
    "name": "werwerwer",
    "sub": "400",
    "preferred_username": "fefefefe",
    "email": "ffdfddf@fsfsfs.com",
    "email_verified": "false",
    "memberType": "Agent",
    "token": "23423423423423"
  },
  "userAuthorization": {
    "roles": [
      "Agent"
    ],
    "permissions": [
      "ViewListings",
      "EditListings",
      "UpdateListings",
      "DeleteListings"
    ]
  },
  "lastScreen": "/dashboard"
```

I can't get this to work. The library requires `name` or some identifier. I thought it could parse standard JSON and take the parent property of a child object as the name?

**Comment by leovo2708** [comment]
Please see my examples

**Comment by IAMtheIAM** [comment]
I did see your examples. And none of those show regular JSON as far as I could see. Can you explain a little better?

**Comment by leovo2708** [comment]
I think it is not hard, you can write a helper to map your JSON to new TreeviewItem.

**Comment by IAMtheIAM** [comment]
No, I'll just use another library where the authors are helpful instead of arrogant and unhelpful. [json-formatter](https://github.com/mohsen1/json-formatter) works fine for me.

**Comment by leovo2708** [comment]
Purpose of this component is to handle checkboxes. But you can do it with your customization which requires you to write more code.
