### ISSUE TITLE
HTML in the text field?

### ISSUE THREAD

**Issue by queejie** [leovo2708/ngx-treeview#5]
Thanks very much for this component!  

I would like to add font-icons for different levels, but the HTML tags show as values.  Is there a way around this?  The code is currently doing something like this:

``
new TreeviewItem({text: '<i class="fa fa-cog"></i> ' + subTree.text, value: subTree.value, collapsed: true, children: children});
``

Is there a templating mechanism for each item, by any chance?

Thanks again,
-dqj

**Comment by queejie** [comment]
Reading through the code, maybe wrapping line 61 in treeview.component.ts in a div and using an [innerHTML] attribute there would be the solution?

**Comment by vanchisel** [comment]
@queejie  This is exactly the feature I've being hoping and searching for, to be able to prepend/append html, images and text to each (item) node in the tree. I was able to extend [zTree](http://www.treejs.cn/v3/main.php#_zTreeInfo)  for JavaScript. For example: 

```
   - Miramar Associates LLC (#185-784-957)
     - Quality Assurance Docket (#45768509) (#457685)
     - Special Education Calendar (#90815201) (#908152)
````
Parents and children will have different/custom images. The #s above are unique to each item/node.

ztree is pure JavaScript, not written for Angular.

**Comment by queejie** [comment]
@vanchisel In the absence of help here I've switched over to using angular2-tree.  That module has extensive templating that allows for complex node displays.

**Comment by vanchisel** [comment]
@queejie Thank you for the heads up. I couldn't get `ngx-treeview` to work either (something about cannot resolve due to source-map-loader) so I switched over to using `zTree` with jQuery. Yeah, I know, in Angular. It's working beautifully. I will check out `Angular2-tree` later. Thanks.

**Comment by leovo2708** [comment]
@queejie I really implemented item template. You can check demo here: https://leovo2708.github.io/ngx-treeview/

**Comment by leovo2708** [comment]
@vanchisel I added more functions in this component but maybe my demo didn't show up these. I will try to update my demo in next time.

**Comment by botumsu** [comment]
I faced with the same problem. I am trying to add icons for each items next to checkbox. Can you add in your demo or give some details how can we add it.

**Comment by leovo2708** [comment]
@botumsu This demo is showing button Delete beside each checkbox => https://leovo2708.github.io/ngx-treeview/#/advanced

**Comment by tedRo** [comment]
I'm using ngx-treeview only.
I want to add items to the tree dynamically. I will prefer to have a button to add at each item level (similar to delete button) and when clicked, an item will be added as its child item. 

Can I do that in a similar way you have demonstrated how to have a delete option? (I'm planning to do so that way..)
I also want to make my items editable. Being able to add custom html to text property of items will be good. 
Require suggestions.

Thank you in advance :)

**Comment by botumsu** [comment]
Thanks, it works.

ps note: When **source code** is opened in that top of demo page, wrong code is shown (https://github.com/leovo2708/ngx-treeview/tree/master/src/demo/city).
But https://github.com/leovo2708/ngx-treeview/tree/master/src/demo/product codes should be shown

**Comment by leovo2708** [comment]
@botumsu Yes, this is my mistake. Thank for your notice. I will update demo right now.
