### ISSUE TITLE
Bundling ngx-treeview for production deployments

### ISSUE THREAD

**Issue by narsivc** [leovo2708/ngx-treeview#52]
Hello, do you have any suggestions on the best way to bundle ngx-treeview js files for production deployments ? I tried to bundle it as follows but though it creates a bundle, it throws a run time exception because TreeviewModule can't be found:

gulpfile.js:

var builder = new systemJSBuilder('./');
builder.config({
    paths: {
        "ngx-treeview/*": "node_modules/ngx-treeview/src/*",
        "angular/core.js": "node_modules/angular/core/angular/core.js",
        "angular/forms.js": "node_modules/angular/forms/angular/forms.js",
        "angular/common.js": "node_modules/angular/common/angular/common.js",
        "angular/platform-browser.js": "node_modules/angular/platform-browser/angular/platform-browser.js",
        "lodash": "node_modules/lodash/lodash.js"
    },
    packages: {
        "ngx-treeview": {main: "index.js", defaultExtension: "js"},
    },
    defaultJSExtensions: true
});

gulp.task('bundle:ngx-treeview', function() {
    builder.bundle('ngx-treeview', 'js/ngxtreeview.js', { normalize: true, runtime: true, sourceMaps: true,
        sourceMapContents: true,
        minify: false,
        mangle: false });
});

Btw, I need to mention that i am able to get it working "without" bundling. But i would much rather bundle in my production site than download 16 separate js files. Any strategies to be able to bundle would be great.

**Comment by leovo2708** [comment]
Sorry, it does not support SystemJS. You should use awesome bundler webpack which integrated in Angular CLI. Thanks. Or please help me to contribute to build a bundle version for SystemJS. Thanks.
