### ISSUE TITLE
Set indeterminate state manually

### ISSUE THREAD

**Issue by rspl-yuvraj** [leovo2708/ngx-treeview#53]
Hello @leovo2708 ,
I know with latest update we get indeterminate state of checkbox by default, but what if I want to set it manually from my code? Or is there any function which can refresh my tree manually?
My scenario:
In my project, I'm using two tree-view parallel on change of T1(TreeView1) item I have to update T2(TreeView2) Item manually from my code. I can set checked property of T2 item to true but I dont get reflection in state of parent node chaeckbox. (It also should be set to indeterminate state). Can you please help me out?

**Comment by leovo2708** [comment]
Please upload your demo, and I will help you.
