### ISSUE TITLE
How to get just the checked item?

### ISSUE THREAD

**Issue by jball98** [leovo2708/ngx-treeview#54]
onSelectedChange(item: TreeviewItem) {
//         downlineItems.forEach(downlineItem => {
//             const item = downlineItem.item;
//             const value = item.value;
//             const texts = [item.text];
//             let parent = downlineItem.parent;
//             while (!_.isNil(parent)) {
//                 texts.push(parent.item.text);
//                 parent = parent.parent;
//             }
//             const reverseTexts = _.reverse(texts);
//             const row = `${reverseTexts.join(' -> ')} : ${value}`;
//
//
//         });

I tried
    onSelectedChange(item: TreeviewItem) {

and that item will return everything as well

How can we just get the single item that was just unchecked/checked?

**Comment by tbiinfotech** [comment]
Have you gotten your answer? Actually I am also looking for the such type of solution. In my case I am looking for to get that item which is just unchecked.
