### ISSUE TITLE
cannot push to children after creating empty array

### ISSUE THREAD

**Issue by jball98** [leovo2708/ngx-treeview#55]
i called children.push after creating an empty array for children and then get the follow message.
unless children is defined and then i push then it will work.
using latest version 1.2.3
core.es5.js?de3d:1020 ERROR TypeError: Cannot read property 'push' of undefined

**Comment by jball98** [comment]
what if user wanted to add children later? there should be a boolean value or something in the config that allows for this. this is for dynamic population.

**Comment by pcvogler** [comment]
I am having this same issue. Is there a solution?

**Comment by pcvogler** [comment]
I was able to work around the issue by initializing the children array with a dummy value {text: '', value: ''} then splicing it out before pushing in the desired children

**Comment by ardentia** [comment]
Hello, was this problem resolved? What @pcvogler suggested works but is more of a workaround than an actual solution.

**Comment by unruledboy** [comment]
exact same problem here. @leovo2708

**Comment by SlimenTN** [comment]
same problem here, any updates please !
