### ISSUE TITLE
Drop down treeview should not be hidden after TreeviewItem array is loaded

### ISSUE THREAD

**Issue by narsivc** [leovo2708/ngx-treeview#56]
I get the TreeviewItem array from a remote call onInint. When the component is displayed it simply shows the All button and only shows the tree only upon click. It also hides on focus change. Is there a way to override this behavior to: Display the tree as soon as the TreeviewItem array is populated ? Also, it shouldn't auto-hide.

**Comment by abelkbil** [comment]
@narsivc code please

**Comment by narsivc** [comment]
Closing this. Using "ngx-treeview" instead of "ngx-dropdown-treeview" solves the problem for me.
