### ISSUE TITLE
Feature: Label config

### ISSUE THREAD

**Issue by ida-e** [leovo2708/ngx-treeview#57]
Hi, 
I have an issue with the unability to change the language on labels, for example I would like if there was a way to set the text for the "All"-label in my treeview. 
I would love if you could fix this setting to an otherwise awesome treeview-plugin!

Best Regards,
Ida

**Comment by leovo2708** [comment]
Use TreeviewConfig to change labels https://github.com/leovo2708/ngx-treeview/blob/master/src/lib/treeview-config.ts

Or you can customize headerTemplate.
