### ISSUE TITLE
Not able to get Parent node value

### ISSUE THREAD

**Issue by arunkumar1811** [leovo2708/ngx-treeview#58]
I have used a config of decoupleChildFromParent= true. But when I check the parent check box, selectedChange event fired with empty array of values. I would like to retrieve the value of selected parent when none of the child is selected.
Please help me out in resolving this.

**Comment by leovo2708** [comment]
selectedChange event should raise only selected leaf nodes. If you want to get list of parent nodes -> use ViewChild to access to component which has public property 'items'.

**Comment by sreedharbukya** [comment]
@leovo2708 , If possible, Please can you give an example for the same.

**Comment by hellodpk** [comment]
@leovo2708 , If possible, Please explain how we can achieve this.
