### ISSUE TITLE
ngxTreeview pipe not working

### ISSUE THREAD

**Issue by redrogers** [leovo2708/ngx-treeview#59]
In the HTML I have ```[items]="TrainObject | ngxTreeview:'textField'"```
In the component I have ```
TrainObject = [{
        "UniqueStoryID": "KCS4034-1506447584",
        "LastUpdated": 1506447671,
        "StartRunTime": "9/26/2017 5:39:44 PM",
        "EndRunTime": "9/26/2017 5:41:11 PM",
        "TrainStoryStatus": "Closed",
        "LeadLocomotiveID": "KCS4034",
        "TrainID": "PSHNO26",
        "GeoFence": {
          "DepartedGeoFence": false,
          "InsideGeoFence": false,
          "Origin": "",
          "Destination": "",
          "DestinationLatitude": "",
          "DestinationLongitude": ""
        }
}]```
I'm getting: A text of item must be string object

Is the JSON supposed to be formatted differently?

**Comment by leovo2708** [comment]
You must give specific text field, example: TrainID
=> so, you will use pipe like this:
`[items]="TrainObject | ngxTreeview:'TrainID'"`
