### ISSUE TITLE
show parent node as selected using minus icon if any child node selected

### ISSUE THREAD

**Issue by dhaval-aspire** [leovo2708/ngx-treeview#6]
I have request if this feature added then it will be very very great and helpful

**Comment by leovo2708** [comment]
In example 4, I demonstrated how to template. It's very easy: https://github.com/leovo2708/ngx-treeview/blob/master/src/lib/treeview.component.ts#L56

**Comment by leovo2708** [comment]
Sorry, I will apply this feature next time. Thank for your idea.

**Comment by nicholasblexrud** [comment]
+1 Any progress on getting this added?

**Comment by leovo2708** [comment]
Yes, it is in my plan.

**Comment by alan12111** [comment]
+1 Any progress on getting this added?

**Comment by tbiinfotech** [comment]
Any updates on this feature?

**Comment by leovo2708** [comment]
I will try to do this, already have a pull request here: https://github.com/leovo2708/ngx-treeview/pulls

**Comment by tbiinfotech** [comment]
I hope this will be added shortly. Good luck and thanks :)

**Comment by leovo2708** [comment]
Supported in new version 1.2.0
