### ISSUE TITLE
how to include the node module of this library in an angular project?

### ISSUE THREAD

**Issue by NVK15** [leovo2708/ngx-treeview#60]
Please see this link: https://stackoverflow.com/questions/46656779/call-to-node-module-failed-with-error-prerendering-failed-because-of-error-err

I get an error:
    ERROR in ./ClientApp/app/app.module.shared.ts
    Module not found: Error: Can't resolve 'ngx-treeview' in '\ClientApp\app'
     @ ./ClientApp/app/app.module.shared.ts 6:21-44

Any help to solve this?

**Comment by leovo2708** [comment]
Sorry, I can't help you to find root cause. But I still keep track this issue.

**Comment by leovo2708** [comment]
Maybe you are using .net core => I update my component to latest version to support Angular 5. Thanks.
