### ISSUE TITLE
treeview loading defaults to select all. 

### ISSUE THREAD

**Issue by sreedharbukya** [leovo2708/ngx-treeview#63]
Hi @leovo2708 ,

I am not able figure out to set default value to select all in current version. 

My use case is default to select all is false. 

Please can you let  me know to do it. 

Thanks in advance.

**Comment by leovo2708** [comment]
Yes, init all of TreeviewItem with checked value is false.

**Comment by sreedharbukya** [comment]
@leovo2708 , 

Is  there any other way to do other than keeping each level as unchecked.

**Comment by leovo2708** [comment]
No, default checked is true. You can write a helper to create a TreeviewItem:
```
function createTreeviewItem(text: string, value: any){
return new TreeviewItem({text: text, value: value, checked: false});
}
```

**Comment by SteffiKeranJ** [comment]
How to initialize the init of all as false?
