### ISSUE TITLE
Disabled is not a property for ngx tree view

### ISSUE THREAD

**Issue by Miteshdv** [leovo2708/ngx-treeview#64]
Hi ,
 I am trying to dynamically enable / disable ngx tree view. But i am getting error disabled is not a property of ngx tree view.
 Please help

**Comment by leovo2708** [comment]
disabled is property of TreeviewItem.
`var item = new TreeviewItem({text: 'text', value: 1, disabled: true});`

**Comment by Miteshdv** [comment]
I want to disable component ngx tree view drop down .. not the node .. pls help

**Comment by Miteshdv** [comment]
I am getting this error
Uncaught Error: Template parse errors:
Can't bind to 'disabled' since it isn't a known property of 'ngx-dropdown-treeview'


I referred ur example

https://github.com/leovo2708/ngx-treeview/blob/master/src/demo/city/city.component.html

Help appreciated

Thanks

**Comment by VijetaH** [comment]
@Miteshdv were you able to resolve this error? If yes can you please share.. I

**Comment by ONbik-srebollo** [comment]
Same here.

I've added disabled property as book example does and it throws an error. I don't understand how this is achieved.
