### ISSUE TITLE
How to get just unchecked Child item's value?

### ISSUE THREAD

**Issue by tbiinfotech** [leovo2708/ngx-treeview#65]
I am passing (selectedChange)="onSelectedChange($event) as parameter in my compoent.html file.

and on component.ts file I am getting this in function as 
```
public onSelectedChange(downlineItems: DownlineTreeviewItem[]) {

}
```
Can anyone please suggest that how can I get just unchecked Child item's value?

**Comment by leovo2708** [comment]
Write a custom TreeviewEventParser, you can access to interface TreeviewParserComponent which has property selection with list of checked items & list of unchecked items.
