### ISSUE TITLE
item.getSelection is not a function

### ISSUE THREAD

**Issue by XiTutang4557** [leovo2708/ngx-treeview#68]
why?找不到问题

**Comment by leovo2708** [comment]
Not clear question

**Comment by EmaGht** [comment]
You declared nodes as Javascript objects and not as TreeViewItem.

![image](https://user-images.githubusercontent.com/12494403/32371352-cc888b4e-c090-11e7-92a5-b67bab00e903.png)

See the example. "node" will throw your error, "node2" will work

**Comment by Abd-exceego** [comment]
@EmaGht how will you add children dynamically according to requirements ..!

**Comment by ravidream** [comment]
TreeViewItem is saying TreeviewComponent.html:47 ERROR TypeError: item.getSelection is not a function

**Comment by ravidream** [comment]
{{values}} also not coming due to this error.

**Comment by Abdul-Quadar-Quazi** [comment]
@ravidream  you can check this here [click here](https://stackoverflow.com/a/45780767)
