### ISSUE TITLE
UI the checkbox not getting updated pro-grammatically 

### ISSUE THREAD

**Issue by chauhanprateek92** [leovo2708/ngx-treeview#69]
I'm using the ngx-treeview for the tree structure, in which the user can expand the list. And also i'm trying to force the user to select only one child item. I'm able to set the values of checkbox and can see the list in the logs, but unfortunately, in the UI the checkbox is not getting updated. Could you please as this is an urgent issue.
Thanks

**Comment by chauhanprateek92** [comment]
![image](https://user-images.githubusercontent.com/17192579/31852955-39702a84-b69e-11e7-952f-7589f4e32c3c.png)

How can I make potato selected and salad unselected? 
Basically, want to restrict the user to select only one item in the entire list. 
Help!

**Comment by leovo2708** [comment]
const treeviewItem = new TreeviewItem({text: 'Salad', value: 1});
treeviewItem.checked = false; // update by programming

**Comment by chauhanprateek92** [comment]
downlineItems.forEach(downlineItem => {
            const item = downlineItem.item;

            if (!item.disabled) {
                if (item.value != 2)
                    item.checked = false;
                let parent = downlineItem.parent;
                while (!_.isNil(parent)) {
                    // texts.push(parent.item.text);
                    if (parent.item.value != currentSelectedFilds)
                        item.checked = false;
                    parent = parent.parent;
                }
            }
        });


I did this but its not working...

**Comment by leovo2708** [comment]
You should use option decoupleChildFromChildren to handle checked yourself.
