### ISSUE TITLE
Arrows to expand/collapse nodes disappeared somewhere...

### ISSUE THREAD

**Issue by Anonymphous** [leovo2708/ngx-treeview#70]
I disabled all custom .css, installed only bootstrap 4 package and ngx-treeview, but there are no arrows in the treeviews.
The <i> element is there, but its height and width are 0px*0px...
![image](https://user-images.githubusercontent.com/30666899/32011690-2e981414-b9be-11e7-8640-ba8a8782b3f3.png)

Any advice would be really appreciated, I'm stuck, and don't know what to fix.

**Comment by leovo2708** [comment]
You missed Font Awesome 4.

**Comment by Anonymphous** [comment]
@leovo2708 Thanks, I was going crazy already!
