### ISSUE TITLE
No scroll-bar in ngx-treeview when 'disabled' in IE11

### ISSUE THREAD

**Issue by petermkruse** [leovo2708/ngx-treeview#71]
I've got **ngx-treeview** inside a *disabled* fieldset. 

When opened in IE11, I'm not able to scroll through the items (no problems when in Firefox and Chrome).

I'm running bootstrap 4.0.0-beta.2 and ngx-treeview 1.2.4

  public config = TreeviewConfig.create({
    hasAllCheckBox: true,
    hasFilter: true,
    hasCollapseExpand: true,
    decoupleChildFromParent: true,
    maxHeight: 500
  }); 

		<fieldset [disabled]="readOnly">
			<p></p>
			<div class="row">
				<div class="col-md-6">
					<div class="col-md-12">
						<label><strong>Menuknapper og transaktioner</strong> *</label>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					<ngx-treeview [config]="config" [items]="items" (selectedChange)="onSelectedChange($event)">
					</ngx-treeview>
				</div>
			</div>

		</fieldset>

**Comment by leovo2708** [comment]
Please reopen issue if this issue still happens
