### ISSUE TITLE
Disable Error

### ISSUE THREAD

**Issue by SebastianRuecker** [leovo2708/ngx-treeview#74]
Hey there,

i got following console error by using the sample code of ngx-treeview (books) in my own app.

> Uncaught
> 
>  Error: Template parse errors:
> Can't bind to 'disabled' since it isn't a known property of 'ngx-dropdown-treeview'.
> 1. If 'ngx-dropdown-treeview' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
> 2. If 'ngx-dropdown-treeview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("Class" (selectedChange)="onChangeSelection($event)"
>                         [ERROR ->][disabled]="!dropdownEnabled"
>                         [ngxDisabledOnSelector]="'button.dropdown-toggl")
> Can't bind to 'ngxDisabledOnSelector' since it isn't a known property of 'ngx-dropdown-treeview'.
> 1. If 'ngx-dropdown-treeview' is an Angular component and it has 'ngxDisabledOnSelector' input, then verify that it is part of this module.
> 2. If 'ngx-dropdown-treeview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ngeSelection($event)"
>                         [disabled]="!dropdownEnabled"
>                         [ERROR ->][ngxDisabledOnSelector]="'button.dropdown-toggle'">

i simply added the following commands to my module 
`import {TreeviewModule} from 'ngx-treeview';` and 
`imports: [TreeviewModule.forRoot(), ... ]`

with the html template for the component
`<ngx-dropdown-treeview [config]="config" [items]="items" [buttonClass]="buttonClass" (selectedChange)="onChangeSelection($event)" [disabled]="!dropdownEnabled" [ngxDisabledOnSelector]="'button.dropdown-toggle'"></ngx-dropdown-treeview>`

i can't find an error. :-(
can you help me?

Regards

**Comment by leovo2708** [comment]
disabled is not a property of ngx-dropdown-treeview. You should read my demo to see how to implement it. Thanks.

**Comment by dineshpillai** [comment]
Ngx-treeview 404 error found.any one help me?

**Comment by ONbik-srebollo** [comment]
> disabled is not a property of ngx-dropdown-treeview. You should read my demo to see how to implement it. Thanks.

You have this on demo:

```          <ngx-dropdown-treeview [config]="config" [items]="items" [buttonClass]="buttonClass" (selectedChange)="values = $event" [disabled]="!dropdownEnabled"
            [ngxDisabledOnSelector]="'button.dropdown-toggle'" (filterChange)="onFilterChange($event)">
          </ngx-dropdown-treeview>```

There is something I can't see, here ngx-dropdown-treeview component is used...
