### ISSUE TITLE
can't bind config as it is not a property of ngx-treeview

### ISSUE THREAD

**Issue by upanshubhat** [leovo2708/ngx-treeview#79]
Uncaught Error: Template parse errors:
**Can't bind to 'config' since it isn't a known property of 'ngx-treeview'.**
1. If 'ngx-treeview' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'ngx-treeview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("          
           <ngx-treeview [ERROR ->][config]="config" [items]="items" (selectedChange)="values = $event"></ngx-treeview>
          </div>"): ng:///AllViewsModule/IndexCriteriaSearchComponent.html@29:25
**Can't bind to 'items' since it isn't a known property of 'ngx-treeview'.**
1. If 'ngx-treeview' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'ngx-treeview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("ee-root [nodes]="nodes" [focused]="true"></tree-root>-->
           <ngx-treeview [config]="config" [ERROR ->][items]="items" (selectedChange)="values = $event"></ngx-treeview>
          </div>
        </div>
"): ng:///xyzFile
'ngx-treeview' is not a known element:
1. If 'ngx-treeview' is an Angular component, then verify that it is part of this module.
2. If 'ngx-treeview' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("w: hidden;">
           
           [ERROR ->]<ngx-treeview [config]="config" [items]="items" (selectedChange)="values = $event"></ngx-treeview>
  "): ng:///xyzFile

**Comment by JayantSogani** [comment]
Hi, I am trying to use <ngx-treeview [config]="config" [items]="items" (selectedChange)="values = $event">. it appears nicely on the page, but i don't have the dropdown to list the children in the of the parent. please suggest is there anything missing ?

**Comment by robela** [comment]
I am facing the same error

**Comment by JayantSogani** [comment]
Hi Robela,
For me it was happening because I forgot to add font awesome library in the angular-cli.json styles tag.

**Comment by JayantSogani** [comment]
Hi Robela,
For me it was happening because I forgot to add font awesome library in the angular-cli.json styles tag.

**Comment by leovo2708** [comment]
Please import module like this: TreeviewModule.forRoot()

**Comment by acedesigns** [comment]
Hi @leovo2708 
I am facing the same problem. Please see my setup below

### app.module.ts
```
import { TreeviewModule } from 'ngx-treeview';
......

@NgModule({
    imports: [
        ........
        TreeviewModule.forRoot(),
        AppRoutingModule
    ],
    declarations: [ AppComponent ],
    providers: [ Title, AuthGuard, AuthService ],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
```

### design.component.html
```html
<div class="form-group">
    <label> <strong> Design Assets </strong> </label>

    <ngx-treeview [config]="TreeConfig" [items]="TreeItems" (selectedChange)="values = $event"> </ngx-treeview>
  </div>
```

### design.component.ts
```
import { Component, OnInit } from '@angular/core';
import { routerTransition } from '../../router.animations';
import { TreeviewItem, TreeviewConfig } from "ngx-treeview";
import { BookService } from './design.service';

@Component({
  selector    : 'app-design',
  templateUrl : './design.component.html',
  styleUrls   : ['./design.component.scss'],
  animations  : [ routerTransition() ],
  providers   : [ BookService ]
})
export class DesignComponent implements OnInit {

  TreeItems : TreeviewItem[];
  values    : number[];

  TreeConfig = TreeviewConfig.create({
    hasAllCheckBox    : true,
    hasFilter         : true,
    hasCollapseExpand : true,
    decoupleChildFromParent: false,
    maxHeight         : 400
  });

  constructor( private service: BookService) { }

  ngOnInit() {
    this.items = this.service.getBooks();
  }

}
```

**Comment by renatohlf** [comment]
I'm facing the same problem.

**Comment by bpg168** [comment]
I am facing the same problem. Is it resolved already? I am not able to find solution, please post the solution, if found already

**Comment by aminkhiar** [comment]
any update on this one??

**Comment by kik-doctor** [comment]
this group is rubbish.
Why not suggest any solution ?

**Comment by rodrigobabel** [comment]
I have the same problem

TreeviewModule.forRoot(), imported but same error:

ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'ngx-dropdown-treeview-select'.
1. If 'ngx-dropdown-treeview-select' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'ngx-dropdown-treeview-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.


I use angular 8.

**Comment by yeshaParmar** [comment]
Hi all,
I have faced the same issue. 
What I tried for the solution is : 

-------------------------------------------------------------------------
**import { TreeviewModule } from 'ngx-treeview';

@NgModule({
    imports: [
        ........
        TreeviewModule.forRoot(),**
-------------------------------------------------------------------------

Write above in the module where you exactly use the code. If your code you have a sub-module DesignModule and you use the code in DesignComponent the import in DesignModule rather then importing in AppModule. 

Hope this will help :)

**Comment by balachander2812** [comment]
Even i faced the issue , it worked for me like.importing the module to sub component module.

**Comment by minaz-metar** [comment]
> Hi all, I have faced the same issue. What I tried for the solution is :
> 
> **import { TreeviewModule } from 'ngx-treeview';
> 
> ## @NgModule({
> imports: [
> ........
> TreeviewModule.forRoot(),**
> Write above in the module where you exactly use the code. If your code you have a sub-module DesignModule and you use the code in DesignComponent the import in DesignModule rather then importing in AppModule.
> 
> Hope this will help :)

getting same issue after your solution implemented
