### ISSUE TITLE
is it possible to map ngx-treeview to system.config.js

### ISSUE THREAD

**Issue by pukuotas** [leovo2708/ngx-treeview#8]
hy, is it possible to map ngx-treeview to system.config.js? Could you show the example of mapping if it is posible?

**Comment by ash53** [comment]
@pukuotas try the following:
 map: {
'ngx-treeview' : 'npm:ngx-treeview/lib'
},
packages: {
"ngx-treeview": { "main": "index.js", "defaultExtension": "js" },
}

**Comment by pukuotas** [comment]
thanks, great. Now could you tell me why it is necessary to add package property even you declare it at map prop.? Why it is not enough to write down like 'npm:ngx-treeview/lib/index.js'?

**Comment by ash53** [comment]
Map just tells the system loader where to look for the installed module and package tells inside that module folder which file you want to run.

**Comment by Chandu200881** [comment]
Please help to configure ngx-treeview in system.config.js file. I'm getting below error
Error: Fetch error: 404 Not Found
  Instantiating http://localhost:8099/ngx-treeview
  Loading http://localhost:4200/clientapp/app.module.js

**Comment by Chandu200881** [comment]
@pukuotas, I tried following:
map: {
'ngx-treeview' : 'npm:ngx-treeview/lib'
},
packages: {
"ngx-treeview": { "main": "index.js", "defaultExtension": "js" },
}
but after installing, could find only src folder instead of lib.
\node_modules\ngx-treeview\src

Please suggest the configuration in system.conifg.js file.

**Comment by pukuotas** [comment]
@Chandu200881  and what`s the content of src? is your app.module ok?

**Comment by leovo2708** [comment]
Sorry, my component does not support SystemJS.

**Comment by Chandu200881** [comment]
@pukuotas , after running the command "npm install ngx-treeview --save" it save all the component of ngx under src folder

**Comment by Chandu200881** [comment]
Is their any way where I can use ngx-treeview in my (MVC & Angular 5 integrated application)? if so please suggest the configuration settings  and usage.
Thanks in advance!

**Comment by leovo2708** [comment]
Yes, you should use Webpack bundler instead of SystemJS.

**Comment by pukuotas** [comment]
@leovo2708 you don't need webpack just because to use treeview. The topic is about to solve problem and  not to change the speed or etc.

**Comment by pukuotas** [comment]
@Chandu200881 it's just a trouble to help you because no details from you. No version you use, no contents you get. You just double posted the same answer that you get src. Src is just a name which often is used for kind of source. And it doesn't tell me anything about it's content. I am using treeview too, but I have 0.0.5 version. So maybe there is a problem because you use newer one. I don't  know because no details from you.  Sorry but it is very difficult to help you. Try to change lib to src in `'ngx-treeview' : 'npm:ngx-treeview/lib'` or kind of. And I don't think that webpack would solve your problem. I use webpack too. But I use it for a speed of performance but not really to reduce problems. Webpack doesn't reduce problem on itself. Basically (shortly) it just speeds it up and it works well, if you **handle it well**

**Comment by pukuotas** [comment]
@Chandu200881  I checked: seems that ngx-treeview has src instead of lib since 1.0.2. Now what is your version of ngx-treeview?
