### ISSUE TITLE
How to remove "All"  text from the tree

### ISSUE THREAD

**Issue by Harinadhreddym** [leovo2708/ngx-treeview#80]
Even if I get to know how to replace it is also fine. Can you give tips to do so?

**Comment by Harinadhreddym** [comment]
Can anyone help?

**Comment by leovo2708** [comment]
There are 2 solutions:
- Use custom template.
- Use custom i18n.

**Comment by Harinadhreddym** [comment]
Thanks for the reply. I will try to describe the problem in detail

**Comment by Harinadhreddym** [comment]
![capture10](https://user-images.githubusercontent.com/33953190/33310897-28caff42-d449-11e7-8a49-325976c3bc51.PNG)

**Comment by leovo2708** [comment]
Do you remove it or change it with another text?

**Comment by Harinadhreddym** [comment]
I want to make Z539... as first line of display. So I am just checking whether any inbuilt feature/property is there to remove "All"

**Comment by Harinadhreddym** [comment]
I want to remove

**Comment by leovo2708** [comment]
Set configuration hasAllCheckBox=false to hide it => done

**Comment by Harinadhreddym** [comment]
Thanks for live support, works fine. I am closing the issue

**Comment by MatheusPetrachin** [comment]
I want to change only the text All, how do I do this? In fact I need to translate it, for "Everything"
