### ISSUE TITLE
Is there a simplest way to replace "fa-caret-down" and "fa-caret-right" with boostrap plus and minus icons

### ISSUE THREAD

**Issue by Harinadhreddym** [leovo2708/ngx-treeview#81]
![capture11](https://user-images.githubusercontent.com/33953190/33311707-b1d4af2a-d44b-11e7-86e2-4fc327975af3.PNG)

**Comment by Harinadhreddym** [comment]
@leovo2708, Do you have working feature for it?

**Comment by Harinadhreddym** [comment]
Hope it won't be taken care by a library but if it is there it will be really awesome, Expecting some comments from you dear friends

**Comment by leovo2708** [comment]
Use custom template
