### ISSUE TITLE
Angular 5 Support

### ISSUE THREAD

**Issue by tibinvpaul** [leovo2708/ngx-treeview#82]
Hey,

I am trying to upgrade my app to Angular 5 but the `ngx-treeview` peer dependancy is preventing me from the upgrade because of the below dependancies. 

1. `@angular/common@^4.0.0`
2. `@angular/core@^4.0.0`
3. `@angular/forms@^4.0.0`

Do we have a plan to upgrade this package so that it can work with Angular 5? Thanks in advance.

**Comment by leovo2708** [comment]
Done. Published in version 2.0.0.
