### ISSUE TITLE
Hide the chechbox feature

### ISSUE THREAD

**Issue by JayantSogani** [leovo2708/ngx-treeview#84]
Hi,

Is there any configuration which supports to remove the checkbox from an element based on some configurations ?

Thanks,

**Comment by leovo2708** [comment]
Using template. See this example: https://leovo2708.github.io/ngx-treeview/#/template

**Comment by JayantSogani** [comment]
Thanks Levovo, but i needed some of the children with checkbox and some without. lets say 
[ ] A
    B
    [ ] C
    [ ] D

here i do not want checkbox for B where as whole tree will be having checkbox.

Thanks,

**Comment by leovo2708** [comment]
Ok, it is easy. TreeviewItem value is an JS object, you can use it as JSON object to store any properties, example: isHasCheckBox and handle it in template to show or hide

**Comment by JayantSogani** [comment]
Hi Leovo,

You mean rebuilding the ngx-treeView to support checkbox (hide/show) ?

Thanks,

**Comment by leovo2708** [comment]
No, you can init a TreeviewItem object like this:
let x = new TreeviewItem({text: 'Item1', value: {hasCheckbox: false, data: 123})
=> use custom template to show or hide item based on item.value.hasCheckbox

**Comment by JayantSogani** [comment]
I got your point, but that doesn't mean rewriting whole thingy ? 
Can you provide any example where i can embed your <ngx-treeview> along with this additional property  or i have to create my own ng-template ?

**Comment by leovo2708** [comment]
No, you don't need to rewrite anything.
See this example: https://leovo2708.github.io/ngx-treeview/#/template

**Comment by JayantSogani** [comment]
You mean to say i have to define [template] and some custom template for eg.

<ng-template #defaultItemTemplate let-item="item" let-onCollapseExpand="onCollapseExpand" let-onCheckedChange="onCheckedChange">
    <div class="form-check">
        <i *ngIf="item.children" (click)="onCollapseExpand()" aria-hidden="true" class="fa" [class.fa-caret-right]="item.collapsed"
            [class.fa-caret-down]="!item.collapsed"></i>
        <label class="form-check-label">
            <input type={{item.hasChecBox}} class="form-check-input"
                [(ngModel)]="item.checked" (ngModelChange)="onCheckedChange()" [disabled]="item.disabled" [indeterminate]="item.indeterminate" />
            {{item.text}}
        </label>
    </div>
</ng-template>

item.hasChecBox can be "hidden" or chechbox as per the input ?

but in this case also i have to write all the method such as onCollapseExpand ??

am i correct ?

Thanks, I am getting confused :(

**Comment by leovo2708** [comment]
Yes, [hidden]="!item.hasCheckBox"
You need to rewrite onCheckedChange, but do not change onCollapseExpand

**Comment by JayantSogani** [comment]
Need to include template in <ngx-treeview> or <ngx-treeview-item> ?

**Comment by JayantSogani** [comment]
Hi Leovo,

I understood somewhat now. thanks man :) i got it i need to write one of my own component as per the one of the new property of treeviewItem to handle the checkbox.  
and have to update the ngx-treeview-item along with the template...

I will try and will let you know.

Thanks,
