### ISSUE TITLE
Getting error when trying to use config options. Cannot read property 'hasFilter' of undefined

### ISSUE THREAD

**Issue by mardon1975** [leovo2708/ngx-treeview#87]
Using ngx-treeview 1.2.5.

The addon works great. Once i try and pass in the configuration options i start getting the following error.

TypeError: Cannot read property 'hasFilter' of undefined at Object.eval [as updateDirectives]

options being passed into the config functionality:
config: {
        hasAllCheckBox: true,
        hasFilter: false,
        hasCollapseExpand: false,
        decoupleChildFromParent: false,
        maxHeight: 500
    }

**Comment by leovo2708** [comment]
Please update new version and try again. Thanks.

**Comment by FelipeFelizardo** [comment]
getting the same error with version     "ngx-treeview": "^6.0.1",

**Comment by soubhikchatterjee** [comment]
Getting same error here as well. Anything can be done to fix this?
