### ISSUE TITLE
Select value of parent element

### ISSUE THREAD

**Issue by absarora** [leovo2708/ngx-treeview#9]
When I select the parent element, I get an array of values for all the child elements. How do I get the value for the selected parent?

**Comment by pukuotas** [comment]
if you have `DownlineTreeviewItem `  array as param in  `onSelectedChange`  func , then you can access parent value by doing:  `downlineItems[i].parent.item.value` . But IMO it works only in cycle. Intelisense works outside the cycle too, but in runtime it says that parent not found/recognized.

**Comment by leovo2708** [comment]
You can use TreeviewHelper which I implemented & exposed in my component. Thanks.

**Comment by helfgod** [comment]
one ?. how i can iterate to retrieve values in n-children??

**Comment by hellodpk** [comment]
@leovo2708  

> TreeviewHelper which I implemented & exposed in my component

I cannot find where, please help.
