### ISSUE TITLE
Question about all check box and indeterminate

### ISSUE THREAD

**Issue by mardon1975** [leovo2708/ngx-treeview#91]
I am running into an issue where when an TreeviewItem is removed from the array, and it was previously checked the All check box still shows the dash in it.

Is there something special I need to do to tell the control none of the child nodes have a check value? I have tried using correctChecked() all over the place but nothing is resetting it.

**Comment by nicholasblexrud** [comment]
@mardon1975 did you find a solution to this?

**Comment by mardon1975** [comment]
Yes and No. Sadly the only way i found to fix the issue is to rebuild the tree with default values from the parent tree.
