### ISSUE TITLE
Try to get the treeview content via REST API

### ISSUE THREAD

**Issue by wavesurfer** [leovo2708/ngx-treeview#94]
HI, I tried to read the treeview data from a Jtree in a JAVA applet, but i didn't succeed. I could build a valid JSON  with a SpringBoot REST API (see https://github.com/mrin9/Angular-SpringBoot-REST-JWT) , but don't get the second part to fill the JSON into the ngx-treeview. Could you build an example, how we can successfully load the whole treeview from a REST API JSON ?

**Comment by leovo2708** [comment]
I can't understand your problem. This is my example with JSON request: https://leovo2708.github.io/ngx-treeview/#/pipe
