### ISSUE TITLE
Can we add custom fields/flags to a new TreeviewItem in ngx-treeview

### ISSUE THREAD

**Issue by tedRo** [leovo2708/ngx-treeview#95]
I'm trying to create a new treeviewItem using  
`let newItem = new TreeviewItem({ 'value': '1', 'text': 'Fruits',
              
                //'hasChildren': true,

                'children': [
                    {
                        'value': '11',
                        'text': 'Apple'

                        //'hasChldern': false,
                        //'parent': '1'

                    }
                ]
            });`

Can my newItem have the (commented here) custom fields (hasChildren and parent)?
I need to have them to make my subsequent tasks easier.

**Comment by leovo2708** [comment]
Yes. but you must inject custom fields in value. Instead of using:
value: '11'
you can define value as JSON object with custom fields: {id: '11', isLeaf: true, parent: '12'}

**Comment by tedRo** [comment]
Thank you @leovo2708 for the prompt reply. 

Does the creation of tree view/ hierarchy depend on children[] or value property of items?
Or do we assign value 1 to our parent item and values 11, 12, 13 and so on...to increase its readability?

**Comment by leovo2708** [comment]
Sorry, I don't save parent node in child node for reference. Only parent node to have reference to children.
