### ISSUE TITLE
Bootstrap v4.0.0

### ISSUE THREAD

**Issue by ida-e** [leovo2708/ngx-treeview#96]
Hey,
Have you thought about supporting the new [Bootstrap v4.0.0](https://getbootstrap.com/)?

**Comment by leovo2708** [comment]
My lastest version is supporting Bootstrap 4.0.0-beta.2. Is there any difference between 4.0 beta and 4.0 final?

**Comment by ida-e** [comment]
Yes there's some major changes, when I switch to the latest Bootstrap v4.0.0, the arrows in the treeview gets hidden behind the checkboxes. 
I would really appreciate if you could look it up, 'cause I would like to use the latest Bootstrap in my page.

**Comment by leovo2708** [comment]
Yes, I see. I am working, you will get new version tomorrow. Thank for requesting.

**Comment by leovo2708** [comment]
Done. Please upgrade to version 2.0.2. Thanks.

**Comment by ida-e** [comment]
Hi again,
I found another issue in Bootstrap v4.0.0, the text-div jumps down when the text gets too long, but I want it to follow 'overflow-x: auto' like it does inside the text-div. 

Look at this screenshot:
![capture](https://user-images.githubusercontent.com/32513585/35684105-2ba6cbc4-0766-11e8-8b09-3f038fe8e090.PNG)

**Comment by leovo2708** [comment]
Ok, I will fix it right now.

**Comment by leovo2708** [comment]
Done, please upgrade to version 2.0.3. Thanks.

**Comment by ida-e** [comment]
Hi, sorry to bug you again,
I wonder if before this update, wasn't the user able to click on the label to check the checkbox? That is not working at the moment anyway. Can you fix it?
