### ISSUE TITLE
TreeViewItem custom JSON key

### ISSUE THREAD

**Issue by 1337r34p3r** [leovo2708/ngx-treeview#97]
Hi,

I'm using a service call to call a JSOn data which is in the same format required in the tree view but the key names are different. But I'm facing the error '_A text of item must be string object_'.

How can I use custom key: value names in the treeview ?

**Comment by leovo2708** [comment]
I don't understand your problem. This is my example with JSON request: https://leovo2708.github.io/ngx-treeview/#/pipe

**Comment by 1337r34p3r** [comment]
{
	"groupName": "Some name",
	"groupSelectionIndicator": "N",
	"groupDisplayIndicator": "Y",
	"groupOrderNumber": "3",
	"specialtyDisplay": [{
			"specialtyCode": "72",
			"specialtyDisplayName": "SDN 1"
		},
		{
			"specialtyCode": "89",
			"specialtyDisplayName": "SDN2"
		}
	]
}

This is my same JSON.
When I try to call TreeviewItem(result) inside a for loop where result is the above json.groupName I'm getting the error `A text of item must be string object`.

**Comment by leovo2708** [comment]
I'm not clear your question. This error will happen when you init a TreeviewItem like this:
{
  text: 1,
  value: 1
}

It should be:
{
  text: '1',
  value: 1
}

Please check your code again. Thanks.

**Comment by dshivrin** [comment]
Hi.
I just encountered this error. In my case the bug was because I used the ngTreeview pipe on a non existing field. [items]="items | ngxTreeview:'make-sure-this-is-currect'".

Or initialize the TreeviewItem with a text and value fields instead. Just not both like I did :)

**Comment by 1337r34p3r** [comment]
In my case the pipe was not working properly. Probably something I was missing. So, I changed the JSON to text and value fields.
