### ISSUE TITLE
Angular 4 Support

### ISSUE THREAD

**Issue by botumsu** [leovo2708/ngx-treeview#99]
When I install ngx-treeview by npm install **ngx-treeview --save**, **ngx-treeview@2.0.2** is installed.

When I try to **npm install** it gives me a warning about **Angular 5** not installed.
But I use Angular 4.
So wont ngx-treeview support **Angular 4** anymore?

**Comment by leovo2708** [comment]
I know you get hard to upgrade from Angular 4 to 5  because of a big change of HttpModule and I'm too. But it's better to support the latest version of Angular :)
